/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View;

import Application.Login;
import Services.IEduSysService;
import Services.NguoiHocService;
import Services.NhanVienService;
import entities.NhanVien;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.List;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.NguoiHocModel;
import model.NhanVienModel;

/**
 *
 * @author ADMIN
 */
public class ViewNguoiHoc extends javax.swing.JPanel {

    /**
     * Creates new form ViewNguoiHoc
     */
    IEduSysService<NguoiHocModel> nhService = new NguoiHocService();
    DefaultTableModel _dTableModel = new DefaultTableModel();
    IEduSysService<NhanVienModel> nvService = new NhanVienService();
    String p_email = "\\w+@\\w+\\.\\w+\\.\\w+";
    String p_sdt = "0[0-9]{9}";

    public ViewNguoiHoc() {
        initComponents();
        btn();
        ngaySinh.setDateFormatString("yyyy-MM-dd");
        ngayDK.setDateFormatString("yyyy-MM-dd");
        loaddata(nhService.getlist());
        lbl_nv.setText(Login.getA());
    }

    void btn() {
        ButtonGroup btn = new ButtonGroup();
        btn.add(rdoNam);
        btn.add(rdoNu);
        rdoNam.setSelected(true);
    }

    String getTenNV(String maNV) {
        for (NhanVienModel nv : nvService.getlist()) {
            if (nv.getmaNV().equals(maNV)) {
                return nv.gethoTen();
            }
        }
        return null;
    }

    NhanVien getNV(String manV) {
        for (NhanVienModel nv : nvService.getlist()) {
            if (nv.gethoTen().equals(manV)) {
                return new NhanVien(manV, nv.getmaNV(), nv.gethoTen(), nv.isvaiTro(), null, null);

            }
        }
        return null;
    }

    void loaddata(List<NguoiHocModel> list) {

        _dTableModel = (DefaultTableModel) tblNH.getModel();
        _dTableModel.setRowCount(0);
        for (NguoiHocModel x : list) {
            _dTableModel.addRow(new Object[]{x.getMaNH(), x.getHoTen(), x.getNgaySinh(), x.isGioiTinh() ? "Nam" : "Nữ", x.getDienThoai(), x.getEmail(), x.getGhiChu(), x.getNhanVien().getHoTen(), x.getNgayDK()});
        }
    }

    void showdetail(int index) {
        txtMaNH.setText(tblNH.getModel().getValueAt(index, 0).toString());
        txtTenNH.setText(tblNH.getModel().getValueAt(index, 1).toString());
        try {
            ngaySinh.setDate(new SimpleDateFormat("yyyy-MM-dd").parse(tblNH.getModel().getValueAt(index, 2).toString()));
            ngayDK.setDate(new SimpleDateFormat("yyyy-MM-dd").parse(tblNH.getModel().getValueAt(index, 8).toString()));
        } catch (ParseException ex) {
            ex.printStackTrace();
        }
        rdoNam.setSelected(tblNH.getModel().getValueAt(index, 3).equals("Nam") ? true : false);
        rdoNu.setSelected(tblNH.getModel().getValueAt(index, 3).equals("Nữ") ? true : false);
        txtDt.setText(tblNH.getModel().getValueAt(index, 4).toString());
        txtEmail.setText(tblNH.getModel().getValueAt(index, 5).toString());
        txtGhiChu.setText(tblNH.getModel().getValueAt(index, 6).toString());
        lbl_nv.setText(tblNH.getModel().getValueAt(index, 7).toString());
    }

    NguoiHocModel getGUI() {
        return new NguoiHocModel(txtMaNH.getText(), txtTenNH.getText(), ngaySinh.getDate(), rdoNam.isSelected() ? true : false, txtDt.getText(), txtEmail.getText(), txtGhiChu.getText(), getNV(lbl_nv.getText()), ngayDK.getDate());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jLabel1 = new javax.swing.JLabel();
        txtMaNH = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtTenNH = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        ngaySinh = new com.toedter.calendar.JDateChooser();
        jLabel4 = new javax.swing.JLabel();
        rdoNam = new javax.swing.JRadioButton();
        rdoNu = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        txtDt = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtGhiChu = new javax.swing.JTextField();
        ngayDK = new com.toedter.calendar.JDateChooser();
        jLabel8 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblNH = new javax.swing.JTable();
        lbl_nv = new javax.swing.JLabel();
        btnXoa = new javax.swing.JButton();
        btnThem = new javax.swing.JButton();
        btnSUa = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        jLabel1.setText("Mã NH");

        jLabel2.setText("Tên NH");

        jLabel3.setText("Ngày sinh");

        jLabel4.setText("Giới Tính");

        rdoNam.setText("Nam");

        rdoNu.setText("Nữ");

        jLabel5.setText("Điện thoại");

        txtDt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtDtMouseClicked(evt);
            }
        });

        jLabel9.setText("Email");

        jLabel10.setText("Ghi Chú");

        jLabel8.setText("Ngày ĐK");

        jLabel6.setText("Nhân Viên");

        tblNH.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã NH", "Tên NH", "Ngày sinh", "Giới Tính", "Điện thoại", "Email", "Ghi Chú", "Nhân Viên", "Ngày ĐK"
            }
        ));
        tblNH.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblNHMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblNH);

        lbl_nv.setText("---------------------");

        btnXoa.setText("Xóa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnSUa.setText("Sửa");
        btnSUa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSUaActionPerformed(evt);
            }
        });

        btnClear.setText("Clear");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel7.setText("Quản lý Người Học");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(16, 16, 16)
                                .addComponent(txtMaNH, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(19, 19, 19)
                                .addComponent(txtTenNH, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(19, 19, 19)
                                .addComponent(ngaySinh, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(rdoNam)
                                .addGap(29, 29, 29)
                                .addComponent(rdoNu)))
                        .addGap(72, 72, 72)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(9, 9, 9)
                                .addComponent(txtDt, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(9, 9, 9)
                                .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(9, 9, 9)
                                .addComponent(txtGhiChu, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lbl_nv, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(9, 9, 9)
                                .addComponent(ngayDK, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(84, 84, 84)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btnThem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnSUa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnXoa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnClear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(295, 295, 295)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 838, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(5, 5, 5)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtDt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(btnThem))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addComponent(btnSUa)
                                .addGap(27, 27, 27)
                                .addComponent(btnXoa)
                                .addGap(28, 28, 28)
                                .addComponent(btnClear))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(12, 12, 12)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtGhiChu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbl_nv))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ngayDK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(txtMaNH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTenNH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ngaySinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(rdoNam)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(rdoNu))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtDtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtDtMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_txtDtMouseClicked

    private void tblNHMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblNHMouseClicked
        // TODO add your handling code here:
        showdetail(tblNH.getSelectedRow());
    }//GEN-LAST:event_tblNHMouseClicked

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        // TODO add your handling code here:

        int count = 0;

        int a = JOptionPane.showConfirmDialog(this, "Bạn có muốn thêm không ?");
        if (a == 0) {
            for (NguoiHocModel x : nhService.getlist()) {
                if (x.getMaNH().equals(txtMaNH.getText())) {
                    count++;
                    JOptionPane.showMessageDialog(this, "Trùng mã");
                    return;
                }
            }
            if (txtMaNH.getText().isEmpty() || txtTenNH.getText().isEmpty() || txtGhiChu.getText().isEmpty() || txtDt.getText().isEmpty() || txtEmail.getText().isEmpty() || lbl_nv.getText().isEmpty()) {
                count++;
                JOptionPane.showMessageDialog(this, "Dữ liệu không được null");
                return;
            }
            if (!txtEmail.getText().matches(p_email)) {
                JOptionPane.showMessageDialog(this, "email khong dung dinh dang");
                count++;
                return;
            }
            if (!txtDt.getText().matches(p_sdt)) {
                JOptionPane.showMessageDialog(this, "SĐT khong dung dinh dang");
                count++;
                return;
            }
            if (count == 0) {
                JOptionPane.showMessageDialog(this, nhService.add(getGUI()));
                loaddata(nhService.getlist());
            }
        }
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnSUaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSUaActionPerformed
        // TODO add your handling code here:
        if (tblNH.getSelectedRow() < 0) {
            JOptionPane.showMessageDialog(this, "Mời bạn chọn ");
            return;
        }
        int count = 0;
        int a = JOptionPane.showConfirmDialog(this, "Bạn có sửa thêm không ?");
        if (a == 0) {
            if (txtMaNH.getText().isEmpty() || txtTenNH.getText().isEmpty() || txtGhiChu.getText().isEmpty() || txtDt.getText().isEmpty() || txtEmail.getText().isEmpty() || lbl_nv.getText().isEmpty()) {
                count++;
                JOptionPane.showMessageDialog(this, "Dữ liệu không được null");
                return;
            }
            if (!txtEmail.getText().matches(p_email)) {
                JOptionPane.showMessageDialog(this, "email khong dung dinh dang");
                count++;
                return;
            }
            if (!txtDt.getText().matches(p_sdt)) {
                JOptionPane.showMessageDialog(this, "SĐT khong dung dinh dang");
                count++;
                return;
            }
            if (count == 0) {
                JOptionPane.showMessageDialog(this, nhService.update(getGUI()));
                loaddata(nhService.getlist());
            }
        }
    }//GEN-LAST:event_btnSUaActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        // TODO add your handling code here:
        if (tblNH.getSelectedRow() < 0) {
            JOptionPane.showMessageDialog(this, "Mời bạn chọn ");
            return;
        }
        int a = JOptionPane.showConfirmDialog(this, "Bạn có muốn Xóa không ?");
        if (a == 0) {
            JOptionPane.showMessageDialog(this, nhService.delete(getGUI()));
            loaddata(nhService.getlist());
            btnClearActionPerformed(evt);
        }
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        // TODO add your handling code here:
        txtMaNH.setText("");
        txtTenNH.setText("");
        txtDt.setText("");
        txtEmail.setText("");
        txtGhiChu.setText("");
        lbl_nv.setText(Login.getA());
        ngayDK.setDateFormatString("");
        ngaySinh.setDateFormatString("");

    }//GEN-LAST:event_btnClearActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnSUa;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnXoa;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_nv;
    private com.toedter.calendar.JDateChooser ngayDK;
    private com.toedter.calendar.JDateChooser ngaySinh;
    private javax.swing.JRadioButton rdoNam;
    private javax.swing.JRadioButton rdoNu;
    private javax.swing.JTable tblNH;
    private javax.swing.JTextField txtDt;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtGhiChu;
    private javax.swing.JTextField txtMaNH;
    private javax.swing.JTextField txtTenNH;
    // End of variables declaration//GEN-END:variables
}
