/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View;

import Services.HocVienService;
import Services.IEduSysService;
import Services.KhoaHocService;
import Services.NguoiHocService;
import entities.KhoaHoc;
import entities.NguoiHoc;
import java.io.File;
import java.io.FileOutputStream;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.HocVienModel;
import model.KhoaHocModel;
import model.NguoiHocModel;
import org.apache.poi.ss.usermodel.Cell;
import org.apache.poi.ss.usermodel.CellType;
import org.apache.poi.xssf.usermodel.XSSFRow;
import org.apache.poi.xssf.usermodel.XSSFSheet;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;

/**
 *
 * @author ADMIN
 */
public class ViewHocVien extends javax.swing.JPanel {

    /**
     * Creates new form ViewHocVien
     */
    DefaultTableModel _dTableModel = new DefaultTableModel();
     IEduSysService<KhoaHocModel> khService;
    NguoiHocService nhService;
    IEduSysService<HocVienModel> hvService;

    public ViewHocVien() {
        initComponents();
        khService = new KhoaHocService();
        nhService = new NguoiHocService();
        hvService = new HocVienService();
        loaddata(hvService.getlist());
        txtmaHV.setText(String.valueOf(0));
        txtmaHV.setEnabled(false);
    }

    String getTenNH(String maNH) {
        for (NguoiHocModel nh : nhService.getlist()) {
            if (nh.getMaNH().equals(maNH)) {
                return nh.getHoTen();
            }
        }
        return null;
    }

    NguoiHoc getNH(String maNH) {
        for (NguoiHocModel nh : nhService.getlist()) {
            if (nh.getMaNH().equals(maNH)) {
                return new NguoiHoc(maNH, nh.getHoTen(), nh.getNgaySinh(), nh.isGioiTinh(), nh.getDienThoai(), nh.getEmail(), nh.getGhiChu(), nh.getNhanVien(), nh.getNgayDK(), null);
            }
        }
        return null;
    }

    KhoaHoc getKH(int maKH) {
        for (KhoaHocModel kh : khService.getlist()) {
            if (kh.getMaKH() == maKH) {
                return new KhoaHoc(maKH, kh.getHocPhi(), kh.getThoiLuong(), kh.getNgayKG(), kh.getGhiChu(), kh.getNgayTao(), kh.getNhanvien(), kh.getChuyenDe(), null);
            }
        }
        return null;
    }

    String getmaNH(String tenNH) {
        for (NguoiHocModel nh : nhService.getlist()) {
            if (nh.getHoTen().equals(tenNH)) {
                return nh.getMaNH();
            }
        }
        return null;
    }

    void loaddata(List<HocVienModel> list) {

        _dTableModel = (DefaultTableModel) tblHV.getModel();
        _dTableModel.setRowCount(0);
        for (HocVienModel x : list) {
            _dTableModel.addRow(new Object[]{x.getMaHV(),
                x.getKhoaHoc().getMaKH(),
                x.getNguoiHoc().getHoTen(),
                x.getDiem()});
        }
    }

    void showdetail(int index) {
        txtmaHV.setText(tblHV.getModel().getValueAt(index, 0).toString());
        txtDiem.setText(tblHV.getModel().getValueAt(index, 3).toString());
        lblKH.setText(tblHV.getModel().getValueAt(index, 1).toString());
        lblNH.setText(getmaNH(tblHV.getModel().getValueAt(index, 2).toString()));

    }

    HocVienModel getGUI() {
        return new HocVienModel(Integer.parseInt(txtmaHV.getText()),
                getKH(Integer.parseInt(lblKH.getText())),
                getNH(lblNH.getText()),
                Double.parseDouble(txtDiem.getText()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtDiem = new javax.swing.JTextField();
        txtmaHV = new javax.swing.JTextField();
        btnThem = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblHV = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        btnKh = new javax.swing.JButton();
        btnNh = new javax.swing.JButton();
        lblKH = new javax.swing.JLabel();
        lblNH = new javax.swing.JLabel();
        btnXuat = new javax.swing.JButton();

        jLabel1.setText("Mã HV");

        jLabel2.setText("Mã KH");

        jLabel3.setText("Tên NH");

        jLabel4.setText("Điểm");

        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnSua.setText("Sửa");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        btnXoa.setText("Xóa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        btnClear.setText("Clear");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        tblHV.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Mã HV", "Mã KH", "Tên NH", "Điểm"
            }
        ));
        tblHV.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblHVMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblHV);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setText("Quản lý Học Viên");

        btnKh.setText("Chọn KH");
        btnKh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKhActionPerformed(evt);
            }
        });

        btnNh.setText("Chọn NH");
        btnNh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNhActionPerformed(evt);
            }
        });

        lblKH.setText("------------");

        lblNH.setText("------------");

        btnXuat.setText("Xuất Exel  ");
        btnXuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXuatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(105, 105, 105)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(btnKh, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(btnNh))
                                        .addGap(32, 32, 32)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(lblNH, javax.swing.GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE)
                                            .addComponent(lblKH, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                    .addComponent(txtmaHV, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtDiem, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(111, 111, 111)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnThem)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnXuat))
                                    .addComponent(btnSua, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnClear)))
                            .addComponent(jScrollPane1)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(214, 214, 214)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(223, 223, 223))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jLabel5)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnThem)
                            .addComponent(btnXuat))
                        .addGap(18, 18, 18)
                        .addComponent(btnSua)
                        .addGap(15, 15, 15)
                        .addComponent(btnXoa)
                        .addGap(25, 25, 25)
                        .addComponent(btnClear))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtmaHV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(btnKh)
                            .addComponent(lblKH))
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(btnNh)
                            .addComponent(lblNH))
                        .addGap(13, 13, 13)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtDiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(33, 33, 33)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(52, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        // TODO add your handling code here:

        int count = 0;
        int a = JOptionPane.showConfirmDialog(this, "Bạn có muốn thêm không ?");
        if (a == 0) {
            if (txtDiem.getText().isEmpty() || lblKH.getText().isEmpty() || lblNH.getText().isEmpty()) {
                count++;
                JOptionPane.showMessageDialog(this, "Dữ liệu không được null");
                return;
            }
            for (HocVienModel x : hvService.getlist()) {
                if (x.getKhoaHoc().getMaKH() == Integer.parseInt(lblKH.getText()) && x.getNguoiHoc().getMaNH().equals(lblNH.getText())) {
                    count++;
                    JOptionPane.showMessageDialog(this, "Học Viên đã tồn tại");
                    return;
                }
            }
            if (count == 0) {
                HocVienModel edit = getGUI();
                edit.setMaHV(0);
                JOptionPane.showMessageDialog(this, hvService.add(edit));
                loaddata(hvService.getlist());
            }
        }
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        // TODO add your handling code here:
        if (tblHV.getSelectedRow() < 0) {
            JOptionPane.showMessageDialog(this, "Mời bạn chọn ");
            return;
        }
        int count = 0;
        int a = JOptionPane.showConfirmDialog(this, "Bạn có muốn thêm không ?");
        if (a == 0) {
            if (txtDiem.getText().isEmpty() || lblKH.getText().isEmpty() || lblNH.getText().isEmpty()) {
                count++;
                JOptionPane.showMessageDialog(this, "Dữ liệu không được null");
                return;
            }
            if (count == 0) {
                JOptionPane.showMessageDialog(this, hvService.update(getGUI()));
                loaddata(hvService.getlist());
            }
        }
    }//GEN-LAST:event_btnSuaActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        // TODO add your handling code here:
        if (tblHV.getSelectedRow() < 0) {
            JOptionPane.showMessageDialog(this, "Mời bạn chọn ");
            return;
        }
        JOptionPane.showMessageDialog(this, hvService.delete(getGUI()));
        loaddata(hvService.getlist());
        btnClearActionPerformed(evt);
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        // TODO add your handling code here:
        txtDiem.setText("");
        lblKH.setText("-------");
        lblNH.setText("-------");
        txtmaHV.setText(String.valueOf(0));
    }//GEN-LAST:event_btnClearActionPerformed

    private void tblHVMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblHVMouseClicked
        // TODO add your handling code here:
        showdetail(tblHV.getSelectedRow());
    }//GEN-LAST:event_tblHVMouseClicked

    private void btnKhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKhActionPerformed
        String a = JOptionPane.showInputDialog("Nhập Mã khóa học :");
        if (!a.matches("\\d+")) {
            JOptionPane.showMessageDialog(this, "Mã khóa học là ký tự số");
            return;
        }
        for (KhoaHocModel x : khService.getlist()) {
            if (x.getMaKH() == Integer.parseInt(a)) {
                lblKH.setText(a);
            }
        }

    }//GEN-LAST:event_btnKhActionPerformed

    private void btnNhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNhActionPerformed
        String a = JOptionPane.showInputDialog("Nhập Mã người học :");
        for (NguoiHocModel x : nhService.getlist()) {
            if (x.getMaNH().equals(a)) {
                lblNH.setText(a);
            }
        }

    }//GEN-LAST:event_btnNhActionPerformed

    private void btnXuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXuatActionPerformed
        // TODO add your handling code here:
        XSSFWorkbook workbook = new XSSFWorkbook();
        XSSFSheet sheet = workbook.createSheet("danhsach");
        XSSFRow row = null;
        Cell cell = null;
        row = sheet.createRow(3);
        cell = row.createCell(0, CellType.STRING);
        cell.setCellValue("STT");

        cell = row.createCell(1, CellType.STRING);
        cell.setCellValue("Mã Học Viên");
        cell = row.createCell(2, CellType.STRING);
        cell.setCellValue("Mã Khóa Học");
        cell = row.createCell(3, CellType.STRING);
        cell.setCellValue("Tên Người học");
        cell = row.createCell(4, CellType.STRING);
        cell.setCellValue("Điểm ");
        try {
            for (int i = 0; i < hvService.getlist().size(); i++) {
                FileOutputStream fis = null;
                row = sheet.createRow(5 + i);
                cell = row.createCell(0, CellType.NUMERIC);
                cell.setCellValue(i + 1);
                cell = row.createCell(1, CellType.STRING);
                cell.setCellValue(hvService.getlist().get(i).getMaHV());
                cell = row.createCell(2, CellType.STRING);
                cell.setCellValue(hvService.getlist().get(i).getKhoaHoc().getMaKH());
                cell = row.createCell(3, CellType.STRING);
                cell.setCellValue(getTenNH(hvService.getlist().get(i).getNguoiHoc().getMaNH()));
                cell = row.createCell(4, CellType.STRING);
                cell.setCellValue(hvService.getlist().get(i).getDiem());
                File f = new File("D://danhsach.xlsx");
                fis = new FileOutputStream(f);
                workbook.write(fis);
                fis.close();

            }
            JOptionPane.showMessageDialog(this, "Xuất thành công");
        } catch (Exception ex) {
            Logger.getLogger(ViewHocVien.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, "Xuất không thành công");

        }


    }//GEN-LAST:event_btnXuatActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnKh;
    private javax.swing.JButton btnNh;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnXoa;
    private javax.swing.JButton btnXuat;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblKH;
    private javax.swing.JLabel lblNH;
    private javax.swing.JTable tblHV;
    private javax.swing.JTextField txtDiem;
    private javax.swing.JTextField txtmaHV;
    // End of variables declaration//GEN-END:variables
}
