/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ASSIGNMENT;

import static java.lang.Thread.sleep;
import java.util.List;
import javax.swing.ButtonGroup;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ADMIN
 */
public class Main extends javax.swing.JFrame implements Runnable {

    /**
     * Creates new form Main
     */
    IConTactService _iPsContact;
    Utilities _utilities;
    DefaultComboBoxModel _deBoxModel;
    DefaultTableModel _dTableModel;
    String path = "D:\\ass.txt";
    PerSonContact _ps;

    public Main() {
        initComponents();
        setLocationRelativeTo(null);
        _iPsContact = new ContactService();
        _utilities = new Utilities();
        _deBoxModel = new DefaultComboBoxModel();
        cbcNamSinh();
        btnGioiTinh();
        btnTimKiem();
        btnSapXep();
        btn_Sua.setEnabled(false);
        btn_Xoa.setEnabled(false);

    }

    void cbcNamSinh() {
        cbx_NamSinh.setModel(new DefaultComboBoxModel(_utilities.getAllYears()));
        cbx_NamSinh.setSelectedItem("2002");
    }

    void btnTimKiem() {
        ButtonGroup btn = new ButtonGroup();
        btn.add(rdo_TheoNguoi);
        btn.add(rdo_TheoTenGanDung);
        btn.add(rdo_TheoSDT);
        rdo_TheoNguoi.setSelected(true);

    }

    void btnSapXep() {
        ButtonGroup btn = new ButtonGroup();
        btn.add(rdo_theoAZ);
        btn.add(rdo_sxTheoZA);
        rdo_theoAZ.setSelected(true);

    }

    void btnGioiTinh() {
        ButtonGroup btn = new ButtonGroup();
        btn.add(rdo_Nam);
        btn.add(rdo_Nu);
        rdo_Nu.setSelected(true);

    }

    void loadData(List<PerSonContact> data) {
        _dTableModel = (DefaultTableModel) tbl_DanhBa.getModel();
        _dTableModel.setRowCount(0);
        int stt = 1;
        for (PerSonContact ct : data) {
            _dTableModel.addRow(new Object[]{stt++, ct.getHo(), ct.getTenDem(), ct.getTen(), ct.getNamSinh(), 2022 - Integer.parseInt(ct.getNamSinh()), ct.getGioiTinh() == 0 ? "Nam" : "Nữ", ct.getSdt1(), ct.getSdt2(), ct.getEmail(), ct.getGhiChu(), ct.getId()});
        }
        _iPsContact.getMaxID();

    }

    PerSonContact getdata() {
        return new PerSonContact(txt_sdt1.getText(), txt_sdt2.getText(), txt_Email.getText(), tarea_GhiChu.getText(), _iPsContact.getMaxID(), txt_Ten.getText(), txt_TenDem.getText(), txt_Ho.getText(), cbx_NamSinh.getSelectedItem().toString(), rdo_Nam.isSelected() ? 0 : 1);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        txt_TimKiem = new javax.swing.JTextField();
        btn_TimKiem = new javax.swing.JButton();
        btn_LoadLaiData = new javax.swing.JButton();
        btn_SapXep = new javax.swing.JButton();
        rdo_theoAZ = new javax.swing.JRadioButton();
        rdo_sxTheoZA = new javax.swing.JRadioButton();
        jLabel11 = new javax.swing.JLabel();
        rdo_TheoNguoi = new javax.swing.JRadioButton();
        rdo_TheoTenGanDung = new javax.swing.JRadioButton();
        rdo_TheoSDT = new javax.swing.JRadioButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbl_DanhBa = new javax.swing.JTable();
        Lbl_text = new javax.swing.JLabel();
        lbl_hour = new javax.swing.JLabel();
        lbl_minute = new javax.swing.JLabel();
        lbl_sec = new javax.swing.JLabel();
        lbl_minutee = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        lbl_hour1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btn_Them = new javax.swing.JButton();
        btn_Sua = new javax.swing.JButton();
        btn_Xoa = new javax.swing.JButton();
        btn_Clear = new javax.swing.JButton();
        btn_DocFille = new javax.swing.JButton();
        btn_GhiFile = new javax.swing.JButton();
        btn_FakeData = new javax.swing.JButton();
        pnl_ThemDanhBa = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txt_Ten = new javax.swing.JTextField();
        txt_TenDem = new javax.swing.JTextField();
        txt_Ho = new javax.swing.JTextField();
        cbx_NamSinh = new javax.swing.JComboBox<>();
        rdo_Nam = new javax.swing.JRadioButton();
        rdo_Nu = new javax.swing.JRadioButton();
        txt_sdt1 = new javax.swing.JTextField();
        txt_sdt2 = new javax.swing.JTextField();
        txt_Email = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tarea_GhiChu = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Tìm kiếm"));

        txt_TimKiem.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txt_TimKiemCaretUpdate(evt);
            }
        });

        btn_TimKiem.setText("Tìm kiếm");

        btn_LoadLaiData.setBackground(new java.awt.Color(255, 255, 0));
        btn_LoadLaiData.setForeground(new java.awt.Color(255, 51, 51));
        btn_LoadLaiData.setText("Load Lại Data");
        btn_LoadLaiData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_LoadLaiDataActionPerformed(evt);
            }
        });

        btn_SapXep.setText("Sắp xếp");

        rdo_theoAZ.setText("Theo tên từ A -> Z");
        rdo_theoAZ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdo_theoAZActionPerformed(evt);
            }
        });

        rdo_sxTheoZA.setText("Theo tên từ Z -> A");
        rdo_sxTheoZA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdo_sxTheoZAActionPerformed(evt);
            }
        });

        jLabel11.setText("Kiểu tìm kiếm");

        rdo_TheoNguoi.setText("Theo người");

        rdo_TheoTenGanDung.setText("Theo tên gần đúng ");

        rdo_TheoSDT.setText("Theo sđt gần đúng ");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(txt_TimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_TimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(rdo_TheoNguoi, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(rdo_TheoTenGanDung)))
                .addGap(34, 34, 34)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rdo_TheoSDT)
                    .addComponent(btn_LoadLaiData, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 179, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_SapXep, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rdo_theoAZ, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rdo_sxTheoZA, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_TimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_TimKiem)
                    .addComponent(btn_LoadLaiData)
                    .addComponent(btn_SapXep))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rdo_theoAZ)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(rdo_TheoSDT)
                                .addComponent(rdo_TheoTenGanDung)
                                .addComponent(rdo_TheoNguoi)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rdo_sxTheoZA))
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, 870, 160));

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Danh bạ"));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tbl_DanhBa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "Họ", "Tên đệm", "Tên ", "Năm Sinh", "Tuổi", "Giới Tính", "SĐT1", "SĐT2", "Email", "Ghi Chú"
            }
        ));
        tbl_DanhBa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_DanhBaMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tbl_DanhBa);

        jPanel3.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 18, 844, 125));

        Lbl_text.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Lbl_text.setForeground(new java.awt.Color(0, 204, 51));
        Lbl_text.setText("       Quản Lý Danh Bạ_Thầy dungna29 cute           ");
        jPanel3.add(Lbl_text, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, -1, -1));

        lbl_hour.setBackground(new java.awt.Color(255, 153, 102));
        lbl_hour.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        lbl_hour.setForeground(new java.awt.Color(0, 51, 51));
        lbl_hour.setText("Giờ ");
        jPanel3.add(lbl_hour, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 190, -1, -1));
        jPanel3.add(lbl_minute, new org.netbeans.lib.awtextra.AbsoluteConstraints(791, 156, 43, -1));

        lbl_sec.setBackground(new java.awt.Color(255, 102, 51));
        lbl_sec.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        lbl_sec.setForeground(new java.awt.Color(0, 51, 51));
        lbl_sec.setText("Giây");
        jPanel3.add(lbl_sec, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 190, -1, -1));

        lbl_minutee.setBackground(new java.awt.Color(255, 102, 102));
        lbl_minutee.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        lbl_minutee.setForeground(new java.awt.Color(0, 51, 51));
        lbl_minutee.setText("Phút");
        jPanel3.add(lbl_minutee, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 190, -1, -1));

        jLabel12.setText(":");
        jPanel3.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 190, 30, 20));

        jLabel14.setText(":");
        jPanel3.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(134, 195, 10, -1));

        lbl_hour1.setBackground(new java.awt.Color(255, 153, 102));
        lbl_hour1.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        lbl_hour1.setForeground(new java.awt.Color(0, 51, 51));
        lbl_hour1.setText("Time :");
        jPanel3.add(lbl_hour1, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 188, 72, -1));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 470, 880, 240));

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("FIANL ASSIGNMENT - QL DANH BẠ");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(283, 0, -1, 32));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Nút chức năng"));

        btn_Them.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btn_Them.setText("Thêm");
        btn_Them.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ThemActionPerformed(evt);
            }
        });

        btn_Sua.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btn_Sua.setText("Sửa");
        btn_Sua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SuaActionPerformed(evt);
            }
        });

        btn_Xoa.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btn_Xoa.setText("Xóa");
        btn_Xoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_XoaActionPerformed(evt);
            }
        });

        btn_Clear.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btn_Clear.setText("Clear");
        btn_Clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ClearActionPerformed(evt);
            }
        });

        btn_DocFille.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btn_DocFille.setText("Đọc file");
        btn_DocFille.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_DocFilleActionPerformed(evt);
            }
        });

        btn_GhiFile.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btn_GhiFile.setText("Ghi file");
        btn_GhiFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_GhiFileActionPerformed(evt);
            }
        });

        btn_FakeData.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btn_FakeData.setText("Fake Data");
        btn_FakeData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_FakeDataActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(btn_Clear, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_FakeData, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(btn_Xoa, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_Sua, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_Them, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_DocFille, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_GhiFile, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_Them)
                    .addComponent(btn_DocFille))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_Sua)
                    .addComponent(btn_GhiFile))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_Xoa)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_Clear)
                .addGap(18, 18, 18)
                .addComponent(btn_FakeData)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 40, 330, 250));

        pnl_ThemDanhBa.setBorder(javax.swing.BorderFactory.createTitledBorder("Thêm danh bạ"));

        jLabel2.setText("Tên :");

        jLabel3.setText("Tên đệm :");

        jLabel4.setText("Họ :");

        jLabel5.setText("Năm sinh :");

        jLabel6.setText("Giới tính :");

        jLabel7.setText("SĐT 1 :");

        jLabel8.setText("SĐT 2 :");

        jLabel9.setText("Email :");

        jLabel10.setText("Ghi chú :");

        cbx_NamSinh.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        rdo_Nam.setText("Nam");

        rdo_Nu.setText("Nữ");

        txt_sdt2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_sdt2ActionPerformed(evt);
            }
        });

        tarea_GhiChu.setColumns(20);
        tarea_GhiChu.setRows(5);
        jScrollPane1.setViewportView(tarea_GhiChu);

        javax.swing.GroupLayout pnl_ThemDanhBaLayout = new javax.swing.GroupLayout(pnl_ThemDanhBa);
        pnl_ThemDanhBa.setLayout(pnl_ThemDanhBaLayout);
        pnl_ThemDanhBaLayout.setHorizontalGroup(
            pnl_ThemDanhBaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_ThemDanhBaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_ThemDanhBaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnl_ThemDanhBaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txt_TenDem)
                    .addComponent(txt_Ten)
                    .addComponent(txt_Ho)
                    .addComponent(cbx_NamSinh, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnl_ThemDanhBaLayout.createSequentialGroup()
                        .addComponent(rdo_Nam, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rdo_Nu, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE)))
                .addGap(26, 26, 26)
                .addGroup(pnl_ThemDanhBaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl_ThemDanhBaLayout.createSequentialGroup()
                        .addGroup(pnl_ThemDanhBaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(pnl_ThemDanhBaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 202, Short.MAX_VALUE)
                            .addComponent(txt_Email)))
                    .addGroup(pnl_ThemDanhBaLayout.createSequentialGroup()
                        .addGroup(pnl_ThemDanhBaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8))
                        .addGap(27, 27, 27)
                        .addGroup(pnl_ThemDanhBaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_sdt1, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE)
                            .addComponent(txt_sdt2))))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        pnl_ThemDanhBaLayout.setVerticalGroup(
            pnl_ThemDanhBaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_ThemDanhBaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_ThemDanhBaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(txt_Ten, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_sdt1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnl_ThemDanhBaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel8)
                    .addComponent(txt_TenDem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_sdt2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnl_ThemDanhBaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel9)
                    .addComponent(txt_Ho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_Email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(pnl_ThemDanhBaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl_ThemDanhBaLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnl_ThemDanhBaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbx_NamSinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnl_ThemDanhBaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(rdo_Nam)
                            .addComponent(rdo_Nu)))
                    .addGroup(pnl_ThemDanhBaLayout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(pnl_ThemDanhBaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );

        getContentPane().add(pnl_ThemDanhBa, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 39, 520, 250));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_FakeDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_FakeDataActionPerformed
        // TODO add your handling code here:
        _iPsContact.fakeData();
        loadData(_iPsContact.getlstContact());
        btn_FakeData.setEnabled(false);
        btn_Sua.setEnabled(true);
        btn_Xoa.setEnabled(true);
    }//GEN-LAST:event_btn_FakeDataActionPerformed

    private void btn_ThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ThemActionPerformed
        // TODO add your handling code here:
        int dem = 0;
        if (txt_Ten.getText().isBlank() || txt_TenDem.getText().isBlank() || txt_Ho.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Không được để trống");
            dem++;
        }
        if (!_utilities.checkSo(txt_sdt1.getText()) || txt_sdt1.getText().isEmpty() || !_utilities.checkSo(txt_sdt2.getText()) || txt_sdt2.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "SĐT phải là số");
            dem++;
        }
        if (!_utilities.checkEmail(txt_Email.getText()) || txt_Email.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Email không đúng định dạng");
            dem++;
        }

        if (dem == 0) {
            JOptionPane.showMessageDialog(this, _iPsContact.add(getdata()));
            loadData(_iPsContact.getlstContact());
        }

    }//GEN-LAST:event_btn_ThemActionPerformed

    private void btn_SuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SuaActionPerformed
        int index = tbl_DanhBa.getSelectedRow();
        if (index < 0) {
            JOptionPane.showMessageDialog(this, "Bạn phải chọn 1 người trên bảng!");
            return;
        }
        int dem = 0;
        if (txt_Ten.getText().isBlank() || txt_TenDem.getText().isBlank() || txt_Ho.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Không được để trống");
            dem++;
        }
        if (!_utilities.checkSo(txt_sdt1.getText()) || txt_sdt1.getText().isEmpty() || !_utilities.checkSo(txt_sdt2.getText()) || txt_sdt2.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "SĐT phải là số");
            dem++;
        }
        if (!_utilities.checkEmail(txt_Email.getText()) || txt_Email.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Email không đúng định dạng");
            dem++;
        }
        if (!_utilities.checkEmail(txt_Email.getText()) || txt_Email.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Email không đúng định dạng");
            dem++;
        }

        if (dem == 0) {
            PerSonContact editer = getdata();
            editer.setId(_ps.getId());
            JOptionPane.showMessageDialog(this, _iPsContact.edit(editer));
            loadData(_iPsContact.getlstContact());
        }
    }//GEN-LAST:event_btn_SuaActionPerformed

    private void btn_ClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ClearActionPerformed
        // TODO add your handling code here:
        btn_Them.setEnabled(true);
        txt_Ten.setText("");
        txt_TenDem.setText("");
        txt_Ho.setText("");
        txt_Email.setText("");
        tarea_GhiChu.setText("");
        txt_sdt1.setText("");
        txt_sdt2.setText("");
        rdo_Nu.setSelected(true);
        cbx_NamSinh.setSelectedItem("2002");
        _iPsContact.getMaxID();
        btn_Sua.setEnabled(false);
        btn_Xoa.setEnabled(false);
    }//GEN-LAST:event_btn_ClearActionPerformed

    private void btn_XoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_XoaActionPerformed
        // TODO add your handling code here:
        int index = tbl_DanhBa.getSelectedRow();

        if (index < 0) {
            JOptionPane.showMessageDialog(this, "Bạn phải chọn 1 người trên bảng!");
            return;
        }
        JOptionPane.showMessageDialog(this, _iPsContact.delete(_iPsContact.getlstContact().get(index).getId()));
        loadData(_iPsContact.getlstContact());
        btn_ClearActionPerformed(evt);

    }//GEN-LAST:event_btn_XoaActionPerformed


    private void tbl_DanhBaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_DanhBaMouseClicked
        // TODO add your handling code here:
        int Clickindex = tbl_DanhBa.getSelectedRow();
        _ps = _iPsContact.getlstContact().get(Clickindex);
        txt_Ho.setText(_ps.getHo());
        txt_TenDem.setText(_ps.getTenDem());
        txt_Ten.setText(_ps.getTen());
        txt_Email.setText(_ps.getEmail());
        tarea_GhiChu.setText(_ps.getGhiChu());
        txt_sdt1.setText(_ps.getSdt1());
        txt_sdt2.setText(_ps.getSdt2());
        rdo_Nam.setSelected(_ps.getGioiTinh() == 0 ? true : false);
        rdo_Nu.setSelected(_ps.getGioiTinh() == 1 ? true : false);
        cbx_NamSinh.setSelectedItem(_ps.getNamSinh());
        btn_Sua.setEnabled(true);
        btn_Xoa.setEnabled(true);


    }//GEN-LAST:event_tbl_DanhBaMouseClicked

    private void btn_LoadLaiDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_LoadLaiDataActionPerformed
        // TODO add your handling code here:
        loadData(_iPsContact.getlstContact());
    }//GEN-LAST:event_btn_LoadLaiDataActionPerformed

    private void btn_DocFilleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_DocFilleActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, _iPsContact.docFile(path));
        loadData(_iPsContact.getlstContact());
    }//GEN-LAST:event_btn_DocFilleActionPerformed

    private void btn_GhiFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_GhiFileActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, _iPsContact.ghiFile(path));
        loadData(_iPsContact.getlstContact());
    }//GEN-LAST:event_btn_GhiFileActionPerformed

    private void txt_TimKiemCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txt_TimKiemCaretUpdate
        if (txt_TimKiem.getText().isEmpty() || txt_TimKiem.getText().isBlank()) {
//            loadData(_iPsContact.getlstContact());
            return;
        }
        loadData(rdo_TheoNguoi.isSelected() ? _iPsContact.findTheoNguoi(txt_TimKiem.getText()) : rdo_TheoTenGanDung.isSelected() ? _iPsContact.findTheoTen(txt_TimKiem.getText()) : _iPsContact.findTheosdt(txt_TimKiem.getText()));
    }//GEN-LAST:event_txt_TimKiemCaretUpdate

    private void rdo_theoAZActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdo_theoAZActionPerformed
        // TODO add your handling code here:
        loadData(_iPsContact.sortAZ());


    }//GEN-LAST:event_rdo_theoAZActionPerformed

    private void rdo_sxTheoZAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdo_sxTheoZAActionPerformed
        // TODO add your handling code here:

        loadData(_iPsContact.sortZA());

    }//GEN-LAST:event_rdo_sxTheoZAActionPerformed

    private void txt_sdt2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_sdt2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_sdt2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new Main().setVisible(true);
//            }
//        });
        Main tam = new Main();
        tam.setVisible(true);
        Thread th = new Thread(tam);
        th.start();

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Lbl_text;
    private javax.swing.JButton btn_Clear;
    private javax.swing.JButton btn_DocFille;
    private javax.swing.JButton btn_FakeData;
    private javax.swing.JButton btn_GhiFile;
    private javax.swing.JButton btn_LoadLaiData;
    private javax.swing.JButton btn_SapXep;
    private javax.swing.JButton btn_Sua;
    private javax.swing.JButton btn_Them;
    private javax.swing.JButton btn_TimKiem;
    private javax.swing.JButton btn_Xoa;
    private javax.swing.JComboBox<String> cbx_NamSinh;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbl_hour;
    private javax.swing.JLabel lbl_hour1;
    private javax.swing.JLabel lbl_minute;
    private javax.swing.JLabel lbl_minutee;
    private javax.swing.JLabel lbl_sec;
    private javax.swing.JPanel pnl_ThemDanhBa;
    private javax.swing.JRadioButton rdo_Nam;
    private javax.swing.JRadioButton rdo_Nu;
    private javax.swing.JRadioButton rdo_TheoNguoi;
    private javax.swing.JRadioButton rdo_TheoSDT;
    private javax.swing.JRadioButton rdo_TheoTenGanDung;
    private javax.swing.JRadioButton rdo_sxTheoZA;
    private javax.swing.JRadioButton rdo_theoAZ;
    private javax.swing.JTextArea tarea_GhiChu;
    private javax.swing.JTable tbl_DanhBa;
    private javax.swing.JTextField txt_Email;
    private javax.swing.JTextField txt_Ho;
    private javax.swing.JTextField txt_Ten;
    private javax.swing.JTextField txt_TenDem;
    private javax.swing.JTextField txt_TimKiem;
    private javax.swing.JTextField txt_sdt1;
    private javax.swing.JTextField txt_sdt2;
    // End of variables declaration//GEN-END:variables

    @Override
    public void run() {
        String chu = Lbl_text.getText();
        int hour = 0;
        int sec = 0;
        int min = 0;
        while (true) {
            char c = chu.charAt(0);
            chu = chu.substring(1, chu.length());
            chu = chu + c;
            Lbl_text.setText(chu);
            try {
                sec++;
                if (sec == 60) {
                    min++;
                    sec = 0;
                }
                if (min == 60) {
                    hour++;
                    min = 0;
                }
                lbl_hour.setText("0" + hour);
                lbl_minutee.setText("0" + min);
                lbl_sec.setText("0" + sec);
                Thread.sleep(1000);
            } catch (Exception e) {
                break;
            }
        }

    }

}
