/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Views;

import Services.NguoiHocService;
import Services.NhanVienServices;
import entities.NguoiHoc;
import entities.NhanVien;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.List;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.NguoiHocModel;
/**
 *
 * @author ADMIN
 */
public class ViewNguoiHoc extends javax.swing.JFrame {

    /**
     * Creates new form ViewNguoiHoc
     */
      NguoiHocService nhService = new NguoiHocService();
   
        DefaultTableModel _dTableModel = new DefaultTableModel();
 NhanVienServices nvServices = new NhanVienServices();
    public ViewNguoiHoc() {
        initComponents();
         btn();
        cbonv();
        ngaySinh.setDateFormatString("yyyy-MM-dd");
        ngayDK.setDateFormatString("yyyy-MM-dd");
        loaddata(nhService.getlist());
    }
      void btn() {
        ButtonGroup btn = new ButtonGroup();
        btn.add(rdoNam);
        btn.add(rdoNu);
        rdoNam.setSelected(true);
    }

    void cbonv() {
        cboNV.removeAllItems();
        for (NhanVien nv : nvServices.getlist()) {
            cboNV.addItem(nv.gethoTen());
        }
    }

    String getTenNV(String maNV) {
        for (NhanVien nv : nvServices.getlist()) {
            if (nv.getmaNV().equals(maNV)) {
                return nv.gethoTen();
            }
        }
        return null;
    }

    String getmaNV(String tenNV) {
        for (NhanVien nv : nvServices.getlist()) {
            if (nv.gethoTen().equals(tenNV)) {
                return nv.getmaNV();
            }
        }
        return null;
    }

    void loaddata(List<NguoiHoc> list) {

        _dTableModel = (DefaultTableModel) tblNH.getModel();
        _dTableModel.setRowCount(0);
        for (NguoiHoc x : list) {
            _dTableModel.addRow(new Object[]{x.getMaNH(), x.getHoTen(), x.getNgaySinh(), x.isGioiTinh() ? " Nam" : "Nữ", x.getDienThoai(), x.getEmail(), x.getGhiChu(), getTenNV(x.getMaNV()), x.getNgayDK()});
        }
    }

    void showdetail(int index) {
        txtMaNH.setText(tblNH.getModel().getValueAt(index, 0).toString());
        txtTenNH.setText(tblNH.getModel().getValueAt(index, 1).toString());
        try {
            ngaySinh.setDate(new SimpleDateFormat("yyyy-MM-dd").parse(tblNH.getModel().getValueAt(index, 2).toString()));
            ngayDK.setDate(new SimpleDateFormat("yyyy-MM-dd").parse(tblNH.getModel().getValueAt(index, 8).toString()));
        } catch (ParseException ex) {
            ex.printStackTrace();
        }
        rdoNam.setSelected(tblNH.getModel().getValueAt(index, 3).equals("Nam") ? true : false);
        rdoNu.setSelected(tblNH.getModel().getValueAt(index, 3).equals("Nữ") ? true : false);
        txtDt.setText(tblNH.getModel().getValueAt(index, 4).toString());
        txtEmail.setText(tblNH.getModel().getValueAt(index, 5).toString());
        txtGhiChu.setText(tblNH.getModel().getValueAt(index, 6).toString());
        for (int i = 0; i < cboNV.getItemCount(); i++) {
            if (getTenNV(nhService.getlist().get(index).getMaNV()).equalsIgnoreCase(cboNV.getItemAt(i))) {
                cboNV.setSelectedIndex(i);
            }
        }
    }

    NguoiHocModel getGUI() {
        return new NguoiHocModel(txtMaNH.getText(), txtTenNH.getText(), ngaySinh.getDate(), rdoNam.isSelected() ? true : false, txtDt.getText(), txtEmail.getText(), txtGhiChu.getText(), getmaNV(cboNV.getSelectedItem().toString()), ngayDK.getDate());
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtMaNH = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtTenNH = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtDt = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        btnThem = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        ngaySinh = new com.toedter.calendar.JDateChooser();
        rdoNam = new javax.swing.JRadioButton();
        rdoNu = new javax.swing.JRadioButton();
        jLabel9 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtGhiChu = new javax.swing.JTextField();
        cboNV = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        ngayDK = new com.toedter.calendar.JDateChooser();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblNH = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel7.setText("Quản lý Người Học");

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Mã NH");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(53, 44, 71, 26));
        jPanel1.add(txtMaNH, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 50, 160, -1));

        jLabel2.setText("Tên NH");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, 71, 26));

        jLabel3.setText("Ngày sinh");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, 71, 26));
        jPanel1.add(txtTenNH, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 90, 160, -1));

        jLabel4.setText("Giới Tính");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, 71, 26));

        jLabel5.setText("Điện thoại");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 40, 71, 26));

        txtDt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtDtMouseClicked(evt);
            }
        });
        jPanel1.add(txtDt, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 40, 150, -1));

        jLabel6.setText("Nhân Viên");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 160, 71, 26));

        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });
        jPanel1.add(btnThem, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 40, -1, -1));

        btnSua.setText("Sửa");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });
        jPanel1.add(btnSua, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 80, 60, -1));

        btnXoa.setText("Xóa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });
        jPanel1.add(btnXoa, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 120, 60, -1));

        btnClear.setText("Clear");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });
        jPanel1.add(btnClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 160, 60, -1));
        jPanel1.add(ngaySinh, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 130, 160, -1));

        rdoNam.setText("Nam");
        jPanel1.add(rdoNam, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 170, -1, -1));

        rdoNu.setText("Nữ");
        jPanel1.add(rdoNu, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 170, -1, -1));

        jLabel9.setText("Email");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 80, 71, 26));
        jPanel1.add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 80, 150, -1));

        jLabel10.setText("Ghi Chú");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 120, 71, 26));
        jPanel1.add(txtGhiChu, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 120, 150, -1));

        cboNV.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(cboNV, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 160, 150, -1));

        jLabel8.setText("Ngày ĐK");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 210, 71, 26));
        jPanel1.add(ngayDK, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 210, 150, -1));

        tblNH.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã NH", "Tên NH", "Ngày sinh", "Giới Tính", "Điện thoại", "Email", "Ghi Chú", "Nhân Viên", "Ngày ĐK"
            }
        ));
        tblNH.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblNHMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblNH);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 873, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(362, 362, 362)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1016, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(134, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(100, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtDtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtDtMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDtMouseClicked

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        // TODO add your handling code here:
        nhService.add(getGUI());
        loaddata(nhService.getlist());
        JOptionPane.showMessageDialog(this, "Thêm thành công");
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        // TODO add your handling code here:
        nhService.update(getGUI());
        loaddata(nhService.getlist());
        JOptionPane.showMessageDialog(this, "Sửa thành công");
    }//GEN-LAST:event_btnSuaActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        // TODO add your handling code here:
        nhService.delete(getGUI());
        loaddata(nhService.getlist());
        JOptionPane.showMessageDialog(this, "Xóa thành công");
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        // TODO add your handling code here:
        txtMaNH.setText("");
        txtTenNH.setText("");
        txtDt.setText("");
        txtEmail.setText("");
        txtGhiChu.setText("");

    }//GEN-LAST:event_btnClearActionPerformed

    private void tblNHMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblNHMouseClicked
        // TODO add your handling code here:
        showdetail(tblNH.getSelectedRow());
    }//GEN-LAST:event_tblNHMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewNguoiHoc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewNguoiHoc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewNguoiHoc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewNguoiHoc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewNguoiHoc().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnXoa;
    private javax.swing.JComboBox<String> cboNV;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private com.toedter.calendar.JDateChooser ngayDK;
    private com.toedter.calendar.JDateChooser ngaySinh;
    private javax.swing.JRadioButton rdoNam;
    private javax.swing.JRadioButton rdoNu;
    private javax.swing.JTable tblNH;
    private javax.swing.JTextField txtDt;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtGhiChu;
    private javax.swing.JTextField txtMaNH;
    private javax.swing.JTextField txtTenNH;
    // End of variables declaration//GEN-END:variables
}
