/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Views;

import Services.ChuyenDeService;
import Services.KhoaHocService;
import Services.NhanVienServices;
import entities.ChuyenDe;
import entities.KhoaHoc;
import entities.NhanVien;
import java.awt.Image;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.KhoaHocModel;

/**
 *
 * @author ADMIN
 */
public class ViewKhoaHoc extends javax.swing.JFrame {

    /**
     * Creates new form ViewKhoaHoc
     */
    NhanVienServices nvService;
    ChuyenDeService cdService;
    KhoaHocService khService;
    DefaultTableModel _dTableModel = new DefaultTableModel();

    public ViewKhoaHoc() {
        initComponents();
        nvService = new NhanVienServices();
        cdService = new ChuyenDeService();
        khService = new KhoaHocService();
        ngayTao.setDateFormatString("yyyy-MM-dd");
        ngayKG.setDateFormatString("yyyy-MM-dd");
        cbonv();
        cbcCD();
        loaddata(khService.getlist());

    }

    void cbonv() {
        cboNV.removeAllItems();
        for (NhanVien nv : nvService.getlist()) {
            cboNV.addItem(nv.gethoTen());
        }
    }

    String getTenNV(String maNV) {
        for (NhanVien nv : nvService.getlist()) {
            if (nv.getmaNV().equals(maNV)) {
                return nv.gethoTen();
            }
        }
        return null;
    }

    String getmaNV(String tenNV) {
        for (NhanVien nv : nvService.getlist()) {
            if (nv.gethoTen().equals(tenNV)) {
                return nv.getmaNV();
            }
        }
        return null;
    }

    void cbcCD() {
        cboCD.removeAllItems();
        for (ChuyenDe cd : cdService.getlist()) {
            cboCD.addItem(cd.getTenCD());
        }
    }

    String getTenCD(String maCD) {
        for (ChuyenDe cd : cdService.getlist()) {
            if (cd.getMaCD().equals(maCD)) {
                return cd.getTenCD();
            }
        }
        return null;
    }

    String getmaCD(String tenCD) {
        for (ChuyenDe cd : cdService.getlist()) {
            if (cd.getTenCD().equals(tenCD)) {
                return cd.getMaCD();
            }
        }
        return null;
    }

    void loaddata(List<KhoaHoc> list) {

        _dTableModel = (DefaultTableModel) tblKH.getModel();
        _dTableModel.setRowCount(0);
        for (KhoaHoc x : list) {
            _dTableModel.addRow(new Object[]{x.getMaKH(), getTenCD(x.getMaCD()), x.getHocPhi(), x.getThoiLuong(), x.getNgayKG(), x.getGhiChu(), getTenNV(x.getMaNV()), x.getNgayDK()});
        }
    }

    void showdetail(int index) {
        txtmaKH.setText(tblKH.getModel().getValueAt(index, 0).toString());
        txthocPhi.setText(tblKH.getModel().getValueAt(index, 2).toString());
        txtThoiLuong.setText(tblKH.getModel().getValueAt(index, 3).toString());
        try {
            ngayKG.setDate(new SimpleDateFormat("yyyy-MM-dd").parse(tblKH.getModel().getValueAt(index, 4).toString()));
            ngayTao.setDate(new SimpleDateFormat("yyyy-MM-dd").parse(tblKH.getModel().getValueAt(index, 7).toString()));
        } catch (ParseException ex) {
            ex.printStackTrace();
        }

        txtGhiChu.setText(tblKH.getModel().getValueAt(index, 5).toString());
        for (int i = 0; i < cboNV.getItemCount(); i++) {
            if (getTenNV(khService.getlist().get(index).getMaNV()).equalsIgnoreCase(cboNV.getItemAt(i))) {
                cboNV.setSelectedIndex(i);
            }
        }

        for (int i = 0; i < cboCD.getItemCount(); i++) {
            if (getTenCD(khService.getlist().get(index).getMaCD()).equalsIgnoreCase(cboCD.getItemAt(i))) {
                cboCD.setSelectedIndex(i);
            }
        }
    }

    KhoaHocModel getGUI() {
        return new KhoaHocModel(Integer.parseInt(txtmaKH.getText()), getmaCD(cboCD.getSelectedItem().toString()), Double.parseDouble(txthocPhi.getText()), Integer.parseInt(txtThoiLuong.getText()), ngayKG.getDate(), txtGhiChu.getText(), getmaNV(cboNV.getSelectedItem().toString()), ngayTao.getDate());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtmaKH = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txthocPhi = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnThem = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        ngayKG = new com.toedter.calendar.JDateChooser();
        jLabel10 = new javax.swing.JLabel();
        txtGhiChu = new javax.swing.JTextField();
        cboCD = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        ngayTao = new com.toedter.calendar.JDateChooser();
        cboNV = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        txtThoiLuong = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblKH = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Mã KH");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(53, 44, 71, 26));

        txtmaKH.setEnabled(false);
        jPanel1.add(txtmaKH, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 50, 160, -1));

        jLabel2.setText("Tên CD");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, 71, 26));

        jLabel3.setText("Ngày KG");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, 71, 26));

        txthocPhi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txthocPhiActionPerformed(evt);
            }
        });
        jPanel1.add(txthocPhi, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 170, 160, -1));

        jLabel4.setText("Học Phí");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, 71, 26));

        jLabel6.setText("Nhân Viên");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 90, 71, 26));

        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });
        jPanel1.add(btnThem, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 40, -1, -1));

        btnSua.setText("Sửa");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });
        jPanel1.add(btnSua, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 80, 60, -1));

        btnXoa.setText("Xóa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });
        jPanel1.add(btnXoa, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 120, 60, -1));

        btnClear.setText("Clear");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });
        jPanel1.add(btnClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 160, 60, -1));
        jPanel1.add(ngayKG, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 130, 160, -1));

        jLabel10.setText("Ghi Chú");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 50, 71, 26));
        jPanel1.add(txtGhiChu, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 50, 150, -1));

        cboCD.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(cboCD, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 90, 160, -1));

        jLabel8.setText("Ngày Tạo");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 130, 71, 26));
        jPanel1.add(ngayTao, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 130, 150, -1));

        cboNV.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(cboNV, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 90, 150, -1));

        jLabel5.setText("Thời Lượng");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 180, -1, -1));

        txtThoiLuong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtThoiLuongActionPerformed(evt);
            }
        });
        jPanel1.add(txtThoiLuong, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 180, 150, -1));

        tblKH.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã KH", "Tên CD", "Học Phí", "Thời Lượng", "Ngày KG", "Ghi Chú", "Nhân Viên", "Ngày Tạo"
            }
        ));
        tblKH.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblKHMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblKH);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel7.setText("Quản lý  Khoa Hoc");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 873, Short.MAX_VALUE)
                            .addComponent(jScrollPane1)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(362, 362, 362)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(167, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(114, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txthocPhiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txthocPhiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txthocPhiActionPerformed

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        // TODO add your handling code here:
        khService.add(getGUI());
        loaddata(khService.getlist());
        JOptionPane.showMessageDialog(this, "Thêm thành công");
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        // TODO add your handling code here:
        khService.update(getGUI());
        loaddata(khService.getlist());
        JOptionPane.showMessageDialog(this, "Sửa thành công");
    }//GEN-LAST:event_btnSuaActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        // TODO add your handling code here:
        khService.delete(getGUI());
        loaddata(khService.getlist());
        JOptionPane.showMessageDialog(this, "Xóa thành công");
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        // TODO add your handling code here:
        txtmaKH.setText("");
        txthocPhi.setText("");
        txtThoiLuong.setText("");
        txtGhiChu.setText("");
    }//GEN-LAST:event_btnClearActionPerformed

    private void txtThoiLuongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtThoiLuongActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtThoiLuongActionPerformed

    private void tblKHMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblKHMouseClicked
        // TODO add your handling code here:
        showdetail(tblKH.getSelectedRow());
    }//GEN-LAST:event_tblKHMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewKhoaHoc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewKhoaHoc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewKhoaHoc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewKhoaHoc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewKhoaHoc().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnXoa;
    private javax.swing.JComboBox<String> cboCD;
    private javax.swing.JComboBox<String> cboNV;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private com.toedter.calendar.JDateChooser ngayKG;
    private com.toedter.calendar.JDateChooser ngayTao;
    private javax.swing.JTable tblKH;
    private javax.swing.JTextField txtGhiChu;
    private javax.swing.JTextField txtThoiLuong;
    private javax.swing.JTextField txthocPhi;
    private javax.swing.JTextField txtmaKH;
    // End of variables declaration//GEN-END:variables
}
