/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Views;

import Services.HocVienService;
import Services.KhoaHocService;
import Services.NguoiHocService;
import entities.HocVien;
import entities.KhoaHoc;
import entities.NguoiHoc;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.HocVienModel;

/**
 *
 * @author ADMIN
 */
public class ViewHocVien extends javax.swing.JFrame {

    /**
     * Creates new form ViewHocVien
     */
    DefaultTableModel _dTableModel = new DefaultTableModel();
    KhoaHocService khService;
    NguoiHocService nhService;
    HocVienService hvService;

    public ViewHocVien() {
        initComponents();
        khService = new KhoaHocService();
        nhService = new NguoiHocService();
        hvService = new HocVienService();
        cbcKH();
        cbcNH();
        loaddata(hvService.getlist());
    }

    void cbcKH() {
        cbcMaKH.removeAllItems();
        for (KhoaHoc kh : khService.getlist()) {
            cbcMaKH.addItem(String.valueOf(kh.getMaKH()));
        }
    }

    void cbcNH() {
        cbcTenNH.removeAllItems();
        for (NguoiHoc nh : nhService.getlist()) {
            cbcTenNH.addItem(nh.getHoTen());
        }
    }

    String getTenNH(String maNH) {
        for (NguoiHoc nh : nhService.getlist()) {
            if (nh.getMaNH().equals(maNH)) {
                return nh.getHoTen();
            }
        }
        return null;
    }

    String getmaNH(String tenNH) {
        for (NguoiHoc nh : nhService.getlist()) {
            if (nh.getHoTen().equals(tenNH)) {
                return nh.getMaNH();
            }
        }
        return null;
    }

    void loaddata(List<HocVien> list) {

        _dTableModel = (DefaultTableModel) tblHV.getModel();
        _dTableModel.setRowCount(0);
        for (HocVien x : list) {
            _dTableModel.addRow(new Object[]{x.getMaHV(), x.getMaKH(), getTenNH(x.getMaNH()), x.getDiem()});
        }
    }

    void showdetail(int index) {
        txtmaHV.setText(tblHV.getModel().getValueAt(index, 0).toString());
        txtDiem.setText(tblHV.getModel().getValueAt(index, 3).toString());
        for (int i = 0; i < cbcTenNH.getItemCount(); i++) {
            if (getTenNH(hvService.getlist().get(index).getMaNH()).equalsIgnoreCase(cbcTenNH.getItemAt(i))) {
                cbcTenNH.setSelectedIndex(i);
            }
        }
        cbcMaKH.setSelectedItem(tblHV.getModel().getValueAt(index, 1).toString());
    }

    HocVienModel getGUI() {
        return new HocVienModel(Integer.parseInt(txtmaHV.getText()), Integer.parseInt(cbcMaKH.getSelectedItem().toString()), getmaNH(cbcTenNH.getSelectedItem().toString()), Double.parseDouble(txtDiem.getText()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtmaHV = new javax.swing.JTextField();
        cbcMaKH = new javax.swing.JComboBox<>();
        cbcTenNH = new javax.swing.JComboBox<>();
        txtDiem = new javax.swing.JTextField();
        btnThem = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblHV = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Mã HV");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 101, 60, -1));

        jLabel2.setText("Mã KH");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 145, 60, -1));

        jLabel3.setText("Tên NH");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 187, 60, -1));

        jLabel4.setText("Điểm");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 224, 37, -1));
        getContentPane().add(txtmaHV, new org.netbeans.lib.awtextra.AbsoluteConstraints(164, 95, 170, -1));

        cbcMaKH.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(cbcMaKH, new org.netbeans.lib.awtextra.AbsoluteConstraints(166, 142, 170, -1));

        cbcTenNH.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(cbcTenNH, new org.netbeans.lib.awtextra.AbsoluteConstraints(166, 184, 170, -1));
        getContentPane().add(txtDiem, new org.netbeans.lib.awtextra.AbsoluteConstraints(164, 224, 170, -1));

        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });
        getContentPane().add(btnThem, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 90, -1, -1));

        btnSua.setText("Sửa");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });
        getContentPane().add(btnSua, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 130, 60, -1));

        btnXoa.setText("Xóa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });
        getContentPane().add(btnXoa, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 170, 60, -1));

        btnClear.setText("Clear");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });
        getContentPane().add(btnClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 220, -1, -1));

        tblHV.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Mã HV", "Mã KH", "Tên NH", "Điểm"
            }
        ));
        tblHV.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblHVMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblHV);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 320, 510, 260));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setText("Quản lý Học Viên");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 40, 190, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblHVMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblHVMouseClicked
        // TODO add your handling code here:
        showdetail(tblHV.getSelectedRow());
    }//GEN-LAST:event_tblHVMouseClicked

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        // TODO add your handling code here:
        hvService.add(getGUI());
        loaddata(hvService.getlist());
        JOptionPane.showMessageDialog(this, "Thêm Thành công");
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        // TODO add your handling code here:
        hvService.update(getGUI());
        loaddata(hvService.getlist());
        JOptionPane.showMessageDialog(this, "Sửa Thành công");
    }//GEN-LAST:event_btnSuaActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        // TODO add your handling code here:
        hvService.delete(getGUI());
        loaddata(hvService.getlist());
        JOptionPane.showMessageDialog(this, "Xóa Thành công");
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        // TODO add your handling code here:
        txtDiem.setText("");
        txtmaHV.setText("");
    }//GEN-LAST:event_btnClearActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewHocVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewHocVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewHocVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewHocVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewHocVien().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnXoa;
    private javax.swing.JComboBox<String> cbcMaKH;
    private javax.swing.JComboBox<String> cbcTenNH;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblHV;
    private javax.swing.JTextField txtDiem;
    private javax.swing.JTextField txtmaHV;
    // End of variables declaration//GEN-END:variables
}
