/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Form;

import Object.DongSP;
import Object.HDCT;
import Object.SanPham;
import Service.DongSPService;
import Service.HDCTService;
import Service.HoaDonService;
import Service.SanPhamService;
import Utilities.Utiliti;
import java.util.List;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ADMIN
 */
public class FormSanPham extends javax.swing.JPanel {

    /**
     * Creates new form FormSanPham
     */
    DongSPService _dPService;
    HDCTService _hdCTService  = new HDCTService();
    SanPhamService _spService;
    DefaultTableModel _dDefaultTableModel;
    Utilities.Utiliti _utUtiliti;

    public FormSanPham() {
        initComponents();
        _dPService = new DongSPService();
        _spService = new SanPhamService();
        _utUtiliti = new Utiliti();
        addCBC();
        loaddata(_spService.getlist());
        _dDefaultTableModel = new DefaultTableModel();
    }

    void addCBC() {
        cbc_dongsp.removeAllItems();
        for (DongSP x : _dPService.getlist()) {
            cbc_dongsp.addItem(x.getTen());
        }
        if (cbc_dongsp.getItemCount() == 1) {
            cbc_dongsp.setSelectedIndex(0);
        }
    }

    int getidDongSP(String txt) {
        for (DongSP x : _dPService.getlist()) {
            if (x.getTen().equals(txt)) {
                return x.getId();
            }
        }
        return -1;
    }

    String getTenDongSP(int a) {
        for (DongSP x : _dPService.getlist()) {
            if (x.getId() == (a)) {
                return x.getTen();
            }
        }
        return null;
    }
    
    String getmasp(int a) {
        for (SanPham x : _spService.getlist()) {
            if (x.getId() == a) {
                return x.getMa();
            }
        }
        return null;
    }
    
     void loaddata(List<SanPham> lits) {
        addCBC();
        if (lits.isEmpty()) {
            return;
        }
        _dDefaultTableModel = (DefaultTableModel) tbl_sp.getModel();
        _dDefaultTableModel.setRowCount(0);
        int stt = 1;
        for (SanPham x : lits) {
            _dDefaultTableModel.addRow(new Object[]{stt,
                x.getMa(),
                x.getTen(),
                x.getNamBaoHanh(),
                x.getTrongLuong(),
                x.getMota(),
                x.getSLSPton(),
                x.getGiaNhap(),
                x.getGiaBan(),
                getTenDongSP(x.getIdDSP())});
            stt++;
        }

    }

    SanPham getGUI() {
        return new SanPham(-1, txt_ma.getText(), txt_ten.getText(), Integer.parseInt(txt_nam.getText()), Float.parseFloat(txt_trongluong.getText()), txt_mota.getText(), Integer.parseInt(txt_slton.getText()), Float.parseFloat(txt_gianhap.getText()), Float.parseFloat(txt_giaban.getText()), getidDongSP(cbc_dongsp.getItemAt(cbc_dongsp.getSelectedIndex())));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txt_ma = new javax.swing.JTextField();
        txt_ten = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txt_nam = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txt_trongluong = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txt_mota = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txt_slton = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txt_gianhap = new javax.swing.JTextField();
        btn_them = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        txt_giaban = new javax.swing.JTextField();
        btn_xoa = new javax.swing.JButton();
        cbc_dongsp = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        btn_sua = new javax.swing.JButton();
        btn_clear = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        txt_timkiem = new javax.swing.JTextField();
        rdb_asc = new javax.swing.JRadioButton();
        rdb_desc = new javax.swing.JRadioButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_sp = new javax.swing.JTable();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Tên");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, 100, 30));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Mã");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, 100, 30));

        txt_ma.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        add(txt_ma, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 70, 160, 30));

        txt_ten.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        add(txt_ten, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 110, 160, 30));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Năm Bảo hành");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, 100, 30));

        txt_nam.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        add(txt_nam, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 150, 160, 30));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Trọng lượng");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 190, 100, 30));

        txt_trongluong.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        add(txt_trongluong, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 190, 160, 30));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Mota");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 230, 100, 30));

        txt_mota.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        add(txt_mota, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 240, 160, 30));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("SL tồn");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 100, 80, 30));

        txt_slton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        add(txt_slton, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 100, 160, 30));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setText("Giá nhập");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 140, 80, 30));

        txt_gianhap.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        add(txt_gianhap, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 140, 160, 30));

        btn_them.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btn_them.setText("Thêm");
        btn_them.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_themActionPerformed(evt);
            }
        });
        add(btn_them, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 240, 90, 40));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setText("Giá bán");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 180, 80, 30));

        txt_giaban.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        add(txt_giaban, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 180, 160, 30));

        btn_xoa.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btn_xoa.setText("Xóa");
        btn_xoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_xoaActionPerformed(evt);
            }
        });
        add(btn_xoa, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 240, 80, 40));

        cbc_dongsp.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cbc_dongsp.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(cbc_dongsp, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 60, 160, 30));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setText("Dòng SP");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 70, -1, -1));

        btn_sua.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btn_sua.setText("Sửa");
        btn_sua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_suaActionPerformed(evt);
            }
        });
        add(btn_sua, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 240, 80, 40));

        btn_clear.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btn_clear.setText("CLEAR");
        btn_clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_clearActionPerformed(evt);
            }
        });
        add(btn_clear, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 240, 100, 40));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel10.setText("QUẢN LÝ SẢN PHẨM");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 20, 240, 30));

        txt_timkiem.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txt_timkiem.setText("Tìm kiếm");
        txt_timkiem.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txt_timkiemCaretUpdate(evt);
            }
        });
        add(txt_timkiem, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 290, 200, 30));

        rdb_asc.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        rdb_asc.setText("ASC");
        rdb_asc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdb_ascActionPerformed(evt);
            }
        });
        add(rdb_asc, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 290, -1, -1));

        rdb_desc.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        rdb_desc.setText("DESC");
        rdb_desc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdb_descActionPerformed(evt);
            }
        });
        add(rdb_desc, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 290, -1, -1));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Thông tin"));

        tbl_sp.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "STT", "Mã", "Tên", "Năm BH", "Trọng lượng", "Môta", "SL tồn", "Giá Nhập", "Giá bán", "Tên Dòng SP"
            }
        ));
        tbl_sp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_spMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_sp);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 754, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, 790, 160));
    }// </editor-fold>//GEN-END:initComponents

    private void btn_themActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_themActionPerformed
        // TODO add your handling code here:

        int count = 0;
        if (txt_ma.getText().isEmpty() || txt_ten.getText().isEmpty() || txt_nam.getText().isEmpty() || txt_trongluong.getText().isEmpty() || txt_mota.getText().isEmpty() || txt_slton.getText().isEmpty() || txt_gianhap.getText().isEmpty() || txt_giaban.getText().isEmpty()) {
            count++;
            JOptionPane.showMessageDialog(this, "Dữ liệu không được null mời bạn nhập lại");
            return;
        }
        if (!_utUtiliti.checkSo(txt_nam.getText()) || !_utUtiliti.checkSo(txt_trongluong.getText()) || !_utUtiliti.checkSo(txt_giaban.getText()) || !_utUtiliti.checkSo(txt_gianhap.getText()) || _utUtiliti.checkSo(txt_ten.getText())) {
            count++;
            JOptionPane.showMessageDialog(this, "Năm, trọng lượng và giá phải là số.Tên là chữ. Mời bạn nhập lại");
            return;
        }
        if (_spService.getIndexByMa(txt_ma.getText()) != -3) {
            JOptionPane.showMessageDialog(this, "Mã trùng");
            return;
        }
        if (count == 0) {
            int a = JOptionPane.showConfirmDialog(this, " Bạn có muốn INSERT không?");
            if (a == 0) {
                JOptionPane.showMessageDialog(this, _spService.store(getGUI(), "INSERT"));
                loaddata(_spService.getlist());
            }
        }
    }//GEN-LAST:event_btn_themActionPerformed

    private void tbl_spMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_spMouseClicked
        // TODO add your handling code here:
        txt_ma.setEnabled(false);
        int index = tbl_sp.getSelectedRow();
        txt_ma.setText(tbl_sp.getModel().getValueAt(index, 1).toString());
        txt_ten.setText(tbl_sp.getModel().getValueAt(index, 2).toString());
        txt_nam.setText(tbl_sp.getModel().getValueAt(index, 3).toString());
        txt_trongluong.setText(tbl_sp.getModel().getValueAt(index, 4).toString());
        txt_mota.setText(tbl_sp.getModel().getValueAt(index, 5).toString());
        txt_slton.setText(tbl_sp.getModel().getValueAt(index, 6).toString());
        txt_gianhap.setText(tbl_sp.getModel().getValueAt(index, 7).toString());
        txt_giaban.setText(tbl_sp.getModel().getValueAt(index, 8).toString());
        for (int i = 0; i < cbc_dongsp.getItemCount(); i++) {
            if (getTenDongSP(_spService.getlist().get(index).getIdDSP()).equalsIgnoreCase(cbc_dongsp.getItemAt(i))) {
                cbc_dongsp.setSelectedIndex(i);
            }
        }
    }//GEN-LAST:event_tbl_spMouseClicked

    private void btn_xoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_xoaActionPerformed
        // TODO add your handling code here:
        addCBC();
        
        int index = tbl_sp.getSelectedRow();
        if (index == -1) {
            JOptionPane.showMessageDialog(this, "Bạn phải chọn");
            return;
        }
        for (int i = 0; i < _hdCTService.getlist().size(); i++) {
            if(_spService.getlist().get(index).getMa().equalsIgnoreCase(getmasp(_hdCTService.getlist().get(i).getIdSanPham()))){
                System.out.println(_hdCTService.getlist().get(i).getIdSanPham());
                JOptionPane.showMessageDialog(this, "Bạn cần xóa sản phẩm trong giỏ hàng");
                return;
            }
        }
        int a = JOptionPane.showConfirmDialog(this, " Bạn có muốn DELETE không?");
        if (a == 0) {
            JOptionPane.showMessageDialog(this, _spService.store(getGUI(), "DELETE"));
            loaddata(_spService.getlist());
            btn_clearActionPerformed(evt);
        }

    }//GEN-LAST:event_btn_xoaActionPerformed

    private void btn_clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_clearActionPerformed
        // TODO add your handling code here:
        txt_ma.setEnabled(true);
        txt_ma.setText("");
        txt_ten.setText("");
        txt_nam.setText("");
        txt_trongluong.setText("");
        txt_mota.setText("");
        txt_slton.setText("");
        txt_gianhap.setText("");
        txt_giaban.setText("");
    }//GEN-LAST:event_btn_clearActionPerformed

    private void btn_suaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_suaActionPerformed
        // TODO add your handling code here:
        int count = 0;
        if ( txt_ten.getText().isEmpty() || txt_nam.getText().isEmpty() || txt_trongluong.getText().isEmpty() || txt_mota.getText().isEmpty() || txt_slton.getText().isEmpty() || txt_gianhap.getText().isEmpty() || txt_giaban.getText().isEmpty()) {
            count++;
            JOptionPane.showMessageDialog(this, "Dữ liệu không được null mời bạn nhập lại");
            return;
        }
        if (!_utUtiliti.checkSo(txt_nam.getText()) || !_utUtiliti.checkSo(txt_trongluong.getText()) || !_utUtiliti.checkSo(txt_giaban.getText()) || !_utUtiliti.checkSo(txt_gianhap.getText()) || _utUtiliti.checkSo(txt_ten.getText())) {
            count++;
            JOptionPane.showMessageDialog(this, "Năm, trọng lượng và giá phải là số.Tên là chữ. Mời bạn nhập lại");
            return;
        }
        if (count == 0) {
            int a = JOptionPane.showConfirmDialog(this, " Bạn có muốn UPDATE không?");
            if (a == 0) {
                JOptionPane.showMessageDialog(this, _spService.store(getGUI(), "UPDATE"));
                loaddata(_spService.getlist());
            }
        }
    }//GEN-LAST:event_btn_suaActionPerformed

    private void rdb_descActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdb_descActionPerformed
        // TODO add your handling code here:
        loaddata(_spService.sort(2));
    }//GEN-LAST:event_rdb_descActionPerformed

    private void txt_timkiemCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txt_timkiemCaretUpdate
        // TODO add your handling code here:
        loaddata(_spService.find(txt_timkiem.getText()));
    }//GEN-LAST:event_txt_timkiemCaretUpdate

    private void rdb_ascActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdb_ascActionPerformed
        // TODO add your handling code here:
        loaddata(_spService.sort(1));
    }//GEN-LAST:event_rdb_ascActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_clear;
    private javax.swing.JButton btn_sua;
    private javax.swing.JButton btn_them;
    private javax.swing.JButton btn_xoa;
    private javax.swing.JComboBox<String> cbc_dongsp;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton rdb_asc;
    private javax.swing.JRadioButton rdb_desc;
    private javax.swing.JTable tbl_sp;
    private javax.swing.JTextField txt_giaban;
    private javax.swing.JTextField txt_gianhap;
    private javax.swing.JTextField txt_ma;
    private javax.swing.JTextField txt_mota;
    private javax.swing.JTextField txt_nam;
    private javax.swing.JTextField txt_slton;
    private javax.swing.JTextField txt_ten;
    private javax.swing.JTextField txt_timkiem;
    private javax.swing.JTextField txt_trongluong;
    // End of variables declaration//GEN-END:variables
}
