/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Form;

import Object.ChucVu;
import Service.CVservice;
import Service.NhanVienService;
import Utilities.Utiliti;
import java.util.List;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ADMIN
 */
public class FormChucVu extends javax.swing.JPanel {

    /**
     * Creates new form FormChucVu
     */
    CVservice _cCVservice;
    DefaultTableModel _dModel;
    ChucVu cv;
    Utilities.Utiliti _uUtiliti;
    NhanVienService _nvService = new NhanVienService();
    public FormChucVu() {
        initComponents();
        _cCVservice = new CVservice();
        _dModel = new DefaultTableModel();
        _uUtiliti = new Utiliti();
        Loaddata(_cCVservice.getlist());
        rdb();
    }

    void Loaddata(List<ChucVu> list) {
        if (list.isEmpty()) {
            _dModel.setRowCount(0);
            return;
        }
        _dModel = (DefaultTableModel) tbl_cv.getModel();
        _dModel.setRowCount(0);

        int stt = 1;
        for (ChucVu x : list) {

            _dModel.addRow(new Object[]{stt, x.getMa(), x.getTen()});
            stt++;
        }
    }

    ChucVu getGUI() {
        return new ChucVu(1, txt_ma.getText(), txt_ten.getText());
    }
     String getSP(int a) {
        for (ChucVu x : _cCVservice.getlist()) {
            if (x.getId()== a) {
                return x.getMa();    
            }
        }
        return null;
     }
    void rdb() {
        ButtonGroup btn = new ButtonGroup();
        btn.add(rdb_asc);
        btn.add(rdb_desc);
        rdb_asc.setSelected(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_cv = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        txt_ma = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txt_ten = new javax.swing.JTextField();
        btn_them = new javax.swing.JButton();
        btn_sua = new javax.swing.JButton();
        btn_xoa = new javax.swing.JButton();
        btn_clear = new javax.swing.JButton();
        txt_timkiem = new javax.swing.JTextField();
        rdb_asc = new javax.swing.JRadioButton();
        rdb_desc = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Table"));

        tbl_cv.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tbl_cv.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "Mã Chức Vụ", "Tên Chúc vụ"
            }
        ));
        tbl_cv.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_cvMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_cv);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 462, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(75, 75, 75))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 270, 500, 200));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("MÃ CV");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, 70, 30));

        txt_ma.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        add(txt_ma, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 100, 180, 30));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Tên CV");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, 70, 30));

        txt_ten.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        add(txt_ten, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 150, 180, 30));

        btn_them.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btn_them.setText("Thêm");
        btn_them.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_themActionPerformed(evt);
            }
        });
        add(btn_them, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 100, 80, 30));

        btn_sua.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btn_sua.setText("Sửa");
        btn_sua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_suaActionPerformed(evt);
            }
        });
        add(btn_sua, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 100, 80, 30));

        btn_xoa.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btn_xoa.setText("Xóa");
        btn_xoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_xoaActionPerformed(evt);
            }
        });
        add(btn_xoa, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 150, 80, 30));

        btn_clear.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btn_clear.setText("Clear");
        btn_clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_clearActionPerformed(evt);
            }
        });
        add(btn_clear, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 150, 80, 30));

        txt_timkiem.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txt_timkiem.setText("Tìm kiếm");
        txt_timkiem.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txt_timkiemCaretUpdate(evt);
            }
        });
        txt_timkiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_timkiemActionPerformed(evt);
            }
        });
        add(txt_timkiem, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 190, 190, 30));

        rdb_asc.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        rdb_asc.setText("ASC");
        rdb_asc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rdb_ascMouseClicked(evt);
            }
        });
        add(rdb_asc, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 230, -1, -1));

        rdb_desc.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        rdb_desc.setText("DESC");
        rdb_desc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdb_descActionPerformed(evt);
            }
        });
        add(rdb_desc, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 230, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("QUẢN LÝ CHỨC VỤ");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 40, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btn_suaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_suaActionPerformed
        // TODO add your handling code here:
        int index = tbl_cv.getSelectedRow();
        int count = 0;
        if (_uUtiliti.checkSo(txt_ten.getText())  || txt_ten.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Mời bạn nhập lại tên");
            count++;
        }
        if (index == -1) {
            JOptionPane.showMessageDialog(this, "Bạn phải chọn");
            return;
        }
        if (count == 0) {
            int a = JOptionPane.showConfirmDialog(this, "Bạn có muốn UPDATE không?");
            if (a == 0) {
                JOptionPane.showMessageDialog(this, _cCVservice.store(getGUI(), "UPDATE"));
                Loaddata(_cCVservice.getlist());
            }
        }

    }//GEN-LAST:event_btn_suaActionPerformed

    private void btn_themActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_themActionPerformed
        int count = 0;
        txt_ma.setEnabled(true);

        if (txt_ma.getText().isEmpty() || _cCVservice.getIndexByMa(txt_ma.getText()) != -3) {
            JOptionPane.showMessageDialog(this, "Mời bạn nhập lại mã");
            count++;
        }
        if (_uUtiliti.checkSo(txt_ten.getText()) || txt_ten.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Mời bạn nhập lại tên");
            count++;
        }
        
        
        if (count == 0) {
            int a = JOptionPane.showConfirmDialog(this, "Bạn có muốn INSERT không");
            if (a == 0) {
                JOptionPane.showMessageDialog(this, _cCVservice.store(getGUI(), "INSERT"));
            }
            Loaddata(_cCVservice.getlist());
        }
    }//GEN-LAST:event_btn_themActionPerformed

    private void btn_xoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_xoaActionPerformed
        int index = tbl_cv.getSelectedRow();
        if (index == -1) {
            JOptionPane.showMessageDialog(this, "Bạn phải chọn");
            return;
        }
 for (int i = 0; i < _nvService.getlist().size(); i++) {
             if(txt_ma.getText().equals(getSP(_nvService.getlist().get(i).getIdCV()))){
             JOptionPane.showMessageDialog(this, "Bạn phải xóa ở bảng SP");
              return;
          }
        
        int a = JOptionPane.showConfirmDialog(this, "Bạn có muốn DELETE không");
        if (a == 0) {
            JOptionPane.showMessageDialog(this, _cCVservice.store(getGUI(), "DELETE"));
            Loaddata(_cCVservice.getlist());
            btn_clearActionPerformed(evt);
        }
        return;
 }


    }//GEN-LAST:event_btn_xoaActionPerformed

    private void btn_clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_clearActionPerformed
        // TODO add your handling code here:
        txt_ma.setEnabled(true);
        txt_ma.setText("");
        txt_ten.setText("");
    }//GEN-LAST:event_btn_clearActionPerformed

    private void rdb_ascMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rdb_ascMouseClicked
        // TODO add your handling code here:
        _cCVservice.sort(1);
        Loaddata(_cCVservice.getlist());
        JOptionPane.showMessageDialog(this, "Bạn đã sắp xếp từ A-Z");


    }//GEN-LAST:event_rdb_ascMouseClicked

    private void rdb_descActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdb_descActionPerformed
        _cCVservice.sort(2);
        Loaddata(_cCVservice.getlist());
        JOptionPane.showMessageDialog(this, "Bạn đã sắp xếp từ Z-A");
    }//GEN-LAST:event_rdb_descActionPerformed

    private void txt_timkiemCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txt_timkiemCaretUpdate
        Loaddata(_cCVservice.find(txt_timkiem.getText()));

    }//GEN-LAST:event_txt_timkiemCaretUpdate

    private void tbl_cvMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_cvMouseClicked
        // TODO add your handling code here:
        txt_ma.setEnabled(false);

        int index = tbl_cv.getSelectedRow();
        String maCv = tbl_cv.getModel().getValueAt(index, 1).toString();//lay gtri tai cell
        System.out.println(maCv);
        txt_ma.setText(maCv);
        txt_ten.setText(tbl_cv.getModel().getValueAt(index, 2).toString());
    }//GEN-LAST:event_tbl_cvMouseClicked

    private void txt_timkiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_timkiemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_timkiemActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_clear;
    private javax.swing.JButton btn_sua;
    private javax.swing.JButton btn_them;
    private javax.swing.JButton btn_xoa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton rdb_asc;
    private javax.swing.JRadioButton rdb_desc;
    private javax.swing.JTable tbl_cv;
    private javax.swing.JTextField txt_ma;
    private javax.swing.JTextField txt_ten;
    private javax.swing.JTextField txt_timkiem;
    // End of variables declaration//GEN-END:variables
}
