/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package BAi5_BTMAu;

import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author ADMIN
 */
public class FrmChucVu extends javax.swing.JFrame {

    /**
     * Creates new form FrmChucVu
     */
    ChucVuService _chuVuService;
    DefaultTableModel _dTableModel;

    public FrmChucVu() {
        initComponents();
        _chuVuService = new ChucVuService();
        _dTableModel = new DefaultTableModel();
        loadTable(_chuVuService.getLstChucVu());
        btn();
    }

    void btn() {
        ButtonGroup btn = new ButtonGroup();
        btn.add(rdb_asc);
        btn.add(rdb_desc);
        rdb_asc.setSelected(true);
    }

    void loadTable(List<ChucVu> list) {
        if (list.isEmpty()) {
            _dTableModel.setRowCount(0);
            return;
        }
        _dTableModel = (DefaultTableModel) tbl_cv.getModel();
        _dTableModel.setRowCount(0);
        int stt = 1;
        for (ChucVu x : list) {
            _dTableModel.addRow(new Object[]{stt, x.getMa(), x.getTen()});
            stt++;
        }
    }

    ChucVu GUIdataControl() {//lay data tu control
        return new ChucVu(-1, txt_ma.getText(), txt_ten.getText());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txt_ma = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txt_ten = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        btn_sua = new javax.swing.JButton();
        btn_them = new javax.swing.JButton();
        btn_xoa = new javax.swing.JButton();
        btn_clear = new javax.swing.JButton();
        rdb_asc = new javax.swing.JRadioButton();
        rdb_desc = new javax.swing.JRadioButton();
        txt_timkiem = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_cv = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Quản lý Chức vụ"));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_ma.setText("jTextField1");
        jPanel1.add(txt_ma, new org.netbeans.lib.awtextra.AbsoluteConstraints(67, 31, 185, 30));

        jLabel1.setText("MÃ CV");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 34, 37, 30));

        jLabel2.setText("Tên CV");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 86, -1, 30));

        txt_ten.setText("jTextField1");
        jPanel1.add(txt_ten, new org.netbeans.lib.awtextra.AbsoluteConstraints(67, 83, 185, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 280, 150));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("cn"));

        btn_sua.setText("Sửa");
        btn_sua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_suaActionPerformed(evt);
            }
        });

        btn_them.setText("Thêm");
        btn_them.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_themActionPerformed(evt);
            }
        });

        btn_xoa.setText("Xóa");
        btn_xoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_xoaActionPerformed(evt);
            }
        });

        btn_clear.setText("Clear");
        btn_clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_clearActionPerformed(evt);
            }
        });

        rdb_asc.setText("ASC");
        rdb_asc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rdb_ascMouseClicked(evt);
            }
        });
        rdb_asc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdb_ascActionPerformed(evt);
            }
        });

        rdb_desc.setText("DESC");
        rdb_desc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdb_descActionPerformed(evt);
            }
        });

        txt_timkiem.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txt_timkiemCaretUpdate(evt);
            }
        });
        txt_timkiem.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_timkiemKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_xoa)
                    .addComponent(btn_sua)
                    .addComponent(btn_them)
                    .addComponent(btn_clear))
                .addGap(21, 21, 21)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(rdb_asc)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 2, Short.MAX_VALUE)
                        .addComponent(rdb_desc))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(txt_timkiem, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_them)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_sua)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_xoa)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btn_clear)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(txt_timkiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(16, 16, 16)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rdb_asc)
                    .addComponent(rdb_desc))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 30, 220, 240));

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Table"));

        tbl_cv.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "Mã Chức Vụ", "Tên Chúc vụ"
            }
        ));
        tbl_cv.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_cvMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_cv);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 411, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(126, 126, 126))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, 460, 310));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_suaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_suaActionPerformed
        // TODO add your handling code here:
        try {
            txt_ma.setEnabled(false);
            JOptionPane.showMessageDialog(this, _chuVuService.update(GUIdataControl()));
            _chuVuService.getlstChucVuFormDb();
            loadTable(_chuVuService.getLstChucVu());
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btn_suaActionPerformed

    private void btn_themActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_themActionPerformed

        try {
            // TODO add your handling code here:
            JOptionPane.showMessageDialog(this, _chuVuService.add(GUIdataControl()));
            _chuVuService.getlstChucVuFormDb();//Mỗi lần insert tc thì sẽ chọc vào db 
            loadTable(_chuVuService.getLstChucVu());
        } catch (SQLException ex) {
            Logger.getLogger(FrmChucVu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_themActionPerformed

    private void tbl_cvMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_cvMouseClicked
        // TODO add your handling code here:
        int index = tbl_cv.getSelectedRow();
        String maCv = tbl_cv.getModel().getValueAt(index, 1).toString();//lay gtri tai cell 
        System.out.println(maCv);
        txt_ma.setText(maCv);
        txt_ten.setText(tbl_cv.getModel().getValueAt(index, 2).toString());
    }//GEN-LAST:event_tbl_cvMouseClicked

    private void btn_xoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_xoaActionPerformed
        // TODO add your handling code here:
        try {
            txt_ma.setEnabled(false);
            JOptionPane.showMessageDialog(this, _chuVuService.delete(GUIdataControl()));
            _chuVuService.getlstChucVuFormDb();//Mỗi lần insert tc thì sẽ chọc vào db 
            loadTable(_chuVuService.getLstChucVu());
        } catch (Exception e) {

        }
    }//GEN-LAST:event_btn_xoaActionPerformed

    private void rdb_descActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdb_descActionPerformed
        // TODO add your handling code here:
        _chuVuService.sort(2);
        loadTable(_chuVuService.getLstChucVu());


    }//GEN-LAST:event_rdb_descActionPerformed

    private void txt_timkiemCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txt_timkiemCaretUpdate
        // TODO add your handling code here:
//        if (txt_timkiem.getText().isEmpty()) {
//            loadTable(_chuVuService.getLstChucVu());
//        }
//        loadTable(_chuVuService.find(txt_timkiem.getText()));

    }//GEN-LAST:event_txt_timkiemCaretUpdate
    public void timSP(JTextField txt, JTable tbl) {
        _dTableModel = (DefaultTableModel) tbl.getModel();
        _dTableModel.fireTableDataChanged();
        TableRowSorter Sorter = new TableRowSorter(_dTableModel);
        tbl.setRowSorter(Sorter);
        Sorter.setRowFilter(RowFilter.regexFilter(txt.getText()));
    }
    private void rdb_ascMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rdb_ascMouseClicked
        // TODO add your handling code here:
        _chuVuService.sort(1);
        loadTable(_chuVuService.getLstChucVu());

    }//GEN-LAST:event_rdb_ascMouseClicked

    private void btn_clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_clearActionPerformed
        // TODO add your handling code here:
        txt_ma.setEnabled(true);
        txt_ma.setText("");
        txt_ten.setText("");

    }//GEN-LAST:event_btn_clearActionPerformed

    private void txt_timkiemKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_timkiemKeyPressed
        // TODO add your handling code here:
        timSP(txt_timkiem, tbl_cv);
    }//GEN-LAST:event_txt_timkiemKeyPressed

    private void rdb_ascActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdb_ascActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdb_ascActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmChucVu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmChucVu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmChucVu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmChucVu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmChucVu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_clear;
    private javax.swing.JButton btn_sua;
    private javax.swing.JButton btn_them;
    private javax.swing.JButton btn_xoa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton rdb_asc;
    private javax.swing.JRadioButton rdb_desc;
    private javax.swing.JTable tbl_cv;
    private javax.swing.JTextField txt_ma;
    private javax.swing.JTextField txt_ten;
    private javax.swing.JTextField txt_timkiem;
    // End of variables declaration//GEN-END:variables
}
