/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package qlsach;

import java.sql.*;
import java.util.List;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ADMIN
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    Connection conn;
    Statement _st;
    PreparedStatement _ps;
    List<sach> _listsv = new ArrayList();
    DefaultTableModel _dTableModel = new DefaultTableModel();

    public Main() {
        initComponents();
        conn = dbconnect.ketnoi("QLSach");
        cbctheloai();
    }

    void cbctheloai() {
        try {
            cbc_tl.removeAllItems();
            String sql = "select * from theloai";
            _st = conn.createStatement();
            ResultSet rs = _st.executeQuery(sql);
            while (rs.next()) {
                cbc_tl.addItem(rs.getString(1));

            }
            cbc_tl.setSelectedIndex(2);
            _st.close();
        } catch (SQLException ex) {
            Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    String getten(String ma) {
        try {
            String sql = "select * from theloai";
            _st = conn.createStatement();
            ResultSet rs = _st.executeQuery(sql);
            while (rs.next()) {
                if (rs.getString(1).equals(ma)) {
                    return rs.getString(2);
                }
            }

            _st.close();

        } catch (Exception e) {
            e.printStackTrace();
        }
        return null;
    }

    List<sach> getlistdata() {
        try {
            List<sach> list = new ArrayList();
            String sql = "select masach,tensach,matheloai,nxb,soluong,giatien from sach where matheloai =?";
            _ps = conn.prepareStatement(sql);
            _ps.setString(1, cbc_tl.getSelectedItem() + "");
            ResultSet rs = _ps.executeQuery();
            while (rs.next()) {
                list.add(new sach(rs.getString(1), rs.getString(2), rs.getString(3), rs.getString(4), rs.getInt(5), rs.getFloat(6)));

            }
            _ps.close();
            return list;

        } catch (SQLException ex) {
            Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
            return null;
        }
    }

    void loadata(List<sach> list) {
        _dTableModel = (DefaultTableModel) tbl_sach.getModel();
        _dTableModel.setRowCount(0);
        for (sach x : list) {
            _dTableModel.addRow(new Object[]{x.getMasach(), x.getTensach(), x.getMaTL(), x.getNxb(), x.getSoluong(), x.getGiaban()});
        }
    }

    void showdetail(int index) {
        txt_ma.setText(tbl_sach.getModel().getValueAt(index, 0).toString());
        txt_ten.setText(tbl_sach.getModel().getValueAt(index, 1).toString());
        txt_nxb.setText(tbl_sach.getModel().getValueAt(index, 3) + "");
        txt_sl.setText(tbl_sach.getModel().getValueAt(index, 4) + "");
        txt_gia.setText(tbl_sach.getModel().getValueAt(index, 5) + "");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cbc_tl = new javax.swing.JComboBox<>();
        lbl_text = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_sach = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txt_ma = new javax.swing.JTextField();
        txt_ten = new javax.swing.JTextField();
        txt_nxb = new javax.swing.JTextField();
        txt_sl = new javax.swing.JTextField();
        txt_gia = new javax.swing.JTextField();
        btn_sua = new javax.swing.JButton();
        btn_xoa = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Thể loại");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 50, 70, 20));

        cbc_tl.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbc_tl.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbc_tlItemStateChanged(evt);
            }
        });
        cbc_tl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cbc_tlMouseClicked(evt);
            }
        });
        getContentPane().add(cbc_tl, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 52, 171, -1));

        lbl_text.setText("jLabel2");
        getContentPane().add(lbl_text, new org.netbeans.lib.awtextra.AbsoluteConstraints(359, 55, 120, -1));

        tbl_sach.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Mã sách", "Tên sách", "Mã TL", "NXB", "Số lượng", "Giá tiền"
            }
        ));
        tbl_sach.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_sachMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_sach);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, 110));

        jLabel2.setText("Mã sách");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 260, -1, -1));

        jLabel3.setText("Tên sách");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 300, -1, -1));

        jLabel4.setText("NXB");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 340, -1, -1));

        jLabel5.setText("Số lượng");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 380, -1, -1));

        jLabel6.setText("jLabel6");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 420, -1, -1));
        getContentPane().add(txt_ma, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 260, 130, -1));
        getContentPane().add(txt_ten, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 300, 130, -1));
        getContentPane().add(txt_nxb, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 340, 130, -1));
        getContentPane().add(txt_sl, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 380, 130, -1));
        getContentPane().add(txt_gia, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 420, 130, -1));

        btn_sua.setText("Update");
        btn_sua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_suaActionPerformed(evt);
            }
        });
        getContentPane().add(btn_sua, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 330, 80, 30));

        btn_xoa.setText("Delete");
        btn_xoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_xoaActionPerformed(evt);
            }
        });
        getContentPane().add(btn_xoa, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 380, 80, 30));

        jButton1.setText("Save");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 280, 80, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbc_tlMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbc_tlMouseClicked
        // TODO add your handling code here:
        loadata(getlistdata());
        if (tbl_sach.getRowCount() > 0) {
            showdetail(0);
        } else {
            txt_ma.setText("");
            txt_gia.setText("");
            txt_ten.setText("");
            txt_sl.setText("");
            txt_nxb.setText("");
        }
    }//GEN-LAST:event_cbc_tlMouseClicked

    private void cbc_tlItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbc_tlItemStateChanged
        // TODO add your handling code here:
        lbl_text.setText(getten(cbc_tl.getSelectedItem() + ""));
        loadata(getlistdata());
        if (tbl_sach.getRowCount() > 0) {
            showdetail(0);
        } else {
            txt_ma.setText("");
            txt_gia.setText("");
            txt_ten.setText("");
            txt_sl.setText("");
            txt_nxb.setText("");
        }
    }//GEN-LAST:event_cbc_tlItemStateChanged

    private void tbl_sachMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_sachMouseClicked
        // TODO add your handling code here:
        int index = tbl_sach.getSelectedRow();
        showdetail(index);
    }//GEN-LAST:event_tbl_sachMouseClicked

    private void btn_suaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_suaActionPerformed
        // TODO add your handling code here:
        int index = tbl_sach.getSelectedRow();
        if(index < 0){
            JOptionPane.showMessageDialog(this, "Bạn chưa chọn ");
        }
        int count = 0;
        if (txt_ma.getText().isEmpty() || txt_ten.getText().isEmpty() || txt_nxb.getText().isEmpty() || txt_sl.getText().isEmpty() || txt_gia.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Dữ liệu không được null");
            count++;
            return;
        }
        if (Integer.parseInt(txt_sl.getText()) < 0) {
            JOptionPane.showMessageDialog(this, "Số lượng > 0");
            count++;
            return;
        }
        if (Float.parseFloat(txt_gia.getText()) < 0) {
            JOptionPane.showMessageDialog(this, "Giá tiền > 0");
            count++;
            return;
        }
        if (count == 0) {
            sua();
        }
    }//GEN-LAST:event_btn_suaActionPerformed

    private void btn_xoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_xoaActionPerformed
        // TODO add your handling code here:
       int index = tbl_sach.getSelectedRow();
        if(index < 0){
            JOptionPane.showMessageDialog(this, "Bạn chưa chọn ");
        }
        xoa();
    }//GEN-LAST:event_btn_xoaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        int count = 0;
        try {
            _st = conn.createStatement();
            ResultSet rs = _st.executeQuery("select masach from sach");
            while (rs.next()) {                
                if(rs.getString(1).equals(txt_ma.getText())){
                    JOptionPane.showMessageDialog(this,"trùng mã");
                    count++;
                    return;
                }
            }
        } catch (SQLException ex) {
            Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        if (txt_ma.getText().isEmpty() || txt_ten.getText().isEmpty() || txt_nxb.getText().isEmpty() || txt_sl.getText().isEmpty() || txt_gia.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Dữ liệu không được null");
            count++;
            return;
        }
        if (Integer.parseInt(txt_sl.getText()) < 0) {
            JOptionPane.showMessageDialog(this, "Số lượng > 0");
            count++;
            return;
        }
        if (Float.parseFloat(txt_gia.getText()) < 0) {
            JOptionPane.showMessageDialog(this, "Giá tiền > 0");
            count++;
            return;
        }
        if (count == 0) {
            them();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_sua;
    private javax.swing.JButton btn_xoa;
    private javax.swing.JComboBox<String> cbc_tl;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_text;
    private javax.swing.JTable tbl_sach;
    private javax.swing.JTextField txt_gia;
    private javax.swing.JTextField txt_ma;
    private javax.swing.JTextField txt_nxb;
    private javax.swing.JTextField txt_sl;
    private javax.swing.JTextField txt_ten;
    // End of variables declaration//GEN-END:variables

    void sua() {
        int a = JOptionPane.showConfirmDialog(this, "Bạn có muốn sua không?");
        if (a == 0) {
            try {
                String sql = "UPDATE sach set tensach=?,matheloai =?,nxb=?,soluong=?,giatien=? where masach =? ";
                _ps = conn.prepareStatement(sql);
                _ps.setString(1, txt_ten.getText());
                _ps.setString(2, cbc_tl.getSelectedItem() + "");
                _ps.setString(3, txt_nxb.getText());
                _ps.setString(4, txt_sl.getText());
                _ps.setString(5, txt_gia.getText());
                _ps.setString(6, txt_ma.getText());
                int b = _ps.executeUpdate();
                if (b > 0) {
                    loadata(getlistdata());
                    JOptionPane.showMessageDialog(this, "Sửa thành công");
                } else {
                    JOptionPane.showMessageDialog(this, "Sửa thất bại");
                }
                _ps.close();
            } catch (SQLException ex) {
                Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }
    
     void them() {
        int a = JOptionPane.showConfirmDialog(this, "Bạn có muốn thêm không?");
        if (a == 0) {
            try {
                String sql = "insert into sach( masach,tensach,matheloai,nxb,soluong,giatien) values (?,?,?,?,?,?)";
                _ps = conn.prepareStatement(sql);
                _ps.setString(1, txt_ma.getText());
                _ps.setString(2, txt_ten.getText());
                _ps.setString(3, cbc_tl.getSelectedItem() + "");
                _ps.setString(4, txt_nxb.getText());
                _ps.setString(5, txt_sl.getText());
                _ps.setString(6, txt_gia.getText());
                
                int b = _ps.executeUpdate();
                if (b > 0) {
                    loadata(getlistdata());
                    JOptionPane.showMessageDialog(this, "Thêm thành công");
                } else {
                    JOptionPane.showMessageDialog(this, "Thêm thất bại");
                }
                _ps.close();
            } catch (SQLException ex) {
                Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }

    void xoa() {
        int a = JOptionPane.showConfirmDialog(this, "Bạn có muốn xóa không?");
        if (a == 0) {
            try {
                String sql = "delete sach where masach =?";
                _ps = conn.prepareStatement(sql);
                _ps.setString(1, txt_ma.getText());
                int b = _ps.executeUpdate();
                if (b > 0) {
                    loadata(getlistdata());
                    JOptionPane.showMessageDialog(this, "Xóa thành công");
                } else {
                    JOptionPane.showMessageDialog(this, "Xóa thất bại");
                }
                _ps.close();
            } catch (SQLException ex) {
                Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }
}
